// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventRecordsColumns holds the columns for the "event_records" table.
	EventRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "session_id", Type: field.TypeString, Nullable: true},
		{Name: "project_id", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "process_run_id", Type: field.TypeString, Default: ""},
		{Name: "node_run_id", Type: field.TypeString, Default: ""},
		{Name: "correlation_id", Type: field.TypeString, Default: ""},
		{Name: "session_status", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// EventRecordsTable holds the schema information for the "event_records" table.
	EventRecordsTable = &schema.Table{
		Name:       "event_records",
		Columns:    EventRecordsColumns,
		PrimaryKey: []*schema.Column{EventRecordsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "eventrecord_project_id_created_at_id",
				Unique:  false,
				Columns: []*schema.Column{EventRecordsColumns[2], EventRecordsColumns[9], EventRecordsColumns[0]},
			},
			{
				Name:    "eventrecord_session_id_created_at_id",
				Unique:  false,
				Columns: []*schema.Column{EventRecordsColumns[1], EventRecordsColumns[9], EventRecordsColumns[0]},
			},
			{
				Name:    "eventrecord_created_at_id",
				Unique:  false,
				Columns: []*schema.Column{EventRecordsColumns[9], EventRecordsColumns[0]},
			},
		},
	}
	// MergeRecordsColumns holds the columns for the "merge_records" table.
	MergeRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "session_id", Type: field.TypeString},
		{Name: "node_run_id", Type: field.TypeString, Nullable: true},
		{Name: "strategy", Type: field.TypeString, Default: ""},
		{Name: "base_branch", Type: field.TypeString, Default: ""},
		{Name: "worktree_branch", Type: field.TypeString, Default: ""},
		{Name: "base_commit", Type: field.TypeString, Default: ""},
		{Name: "head_commit", Type: field.TypeString, Default: ""},
		{Name: "merge_commit", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: ""},
		{Name: "failure_code", Type: field.TypeString, Default: ""},
		{Name: "failure_reason", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "merged_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// MergeRecordsTable holds the schema information for the "merge_records" table.
	MergeRecordsTable = &schema.Table{
		Name:       "merge_records",
		Columns:    MergeRecordsColumns,
		PrimaryKey: []*schema.Column{MergeRecordsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mergerecord_session_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{MergeRecordsColumns[1], MergeRecordsColumns[13]},
			},
		},
	}
	// NodeRunsColumns holds the columns for the "node_runs" table.
	NodeRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "session_id", Type: field.TypeString},
		{Name: "node_id", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "attempt", Type: field.TypeInt, Default: 1},
		{Name: "process_run_id", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "output", Type: field.TypeJSON},
	}
	// NodeRunsTable holds the schema information for the "node_runs" table.
	NodeRunsTable = &schema.Table{
		Name:       "node_runs",
		Columns:    NodeRunsColumns,
		PrimaryKey: []*schema.Column{NodeRunsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "noderun_session_id_node_id",
				Unique:  false,
				Columns: []*schema.Column{NodeRunsColumns[1], NodeRunsColumns[2]},
			},
			{
				Name:    "noderun_session_id_status",
				Unique:  false,
				Columns: []*schema.Column{NodeRunsColumns[1], NodeRunsColumns[3]},
			},
		},
	}
	// ProcessRunsColumns holds the columns for the "process_runs" table.
	ProcessRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "session_id", Type: field.TypeString},
		{Name: "node_run_id", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString},
		{Name: "pid", Type: field.TypeInt, Nullable: true},
		{Name: "codex_session_id", Type: field.TypeString, Default: ""},
		{Name: "transcript_relative_path", Type: field.TypeString, Default: ""},
		{Name: "transcript_bound_at", Type: field.TypeTime, Nullable: true},
		{Name: "resume_of", Type: field.TypeString, Nullable: true},
		{Name: "exit_code", Type: field.TypeInt, Nullable: true},
		{Name: "failure_reason", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
	}
	// ProcessRunsTable holds the schema information for the "process_runs" table.
	ProcessRunsTable = &schema.Table{
		Name:       "process_runs",
		Columns:    ProcessRunsColumns,
		PrimaryKey: []*schema.Column{ProcessRunsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "processrun_session_id_status",
				Unique:  false,
				Columns: []*schema.Column{ProcessRunsColumns[1], ProcessRunsColumns[3]},
			},
			{
				Name:    "processrun_session_id_started_at",
				Unique:  false,
				Columns: []*schema.Column{ProcessRunsColumns[1], ProcessRunsColumns[11]},
			},
			{
				Name:    "processrun_session_id_codex_session_id_transcript_bound_at",
				Unique:  false,
				Columns: []*schema.Column{ProcessRunsColumns[1], ProcessRunsColumns[5], ProcessRunsColumns[7]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "is_git", Type: field.TypeBool, Default: false},
		{Name: "worktree_init_command", Type: field.TypeString, Default: ""},
		{Name: "default_workflow_id", Type: field.TypeString, Nullable: true},
		{Name: "removed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "project_path",
				Unique:  true,
				Columns: []*schema.Column{ProjectsColumns[2]},
			},
		},
	}
	// PromptAppendsColumns holds the columns for the "prompt_appends" table.
	PromptAppendsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "session_id", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "artifact_ids", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "dispatched_at", Type: field.TypeTime, Nullable: true},
		{Name: "dispatched_process_run_id", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PromptAppendsTable holds the schema information for the "prompt_appends" table.
	PromptAppendsTable = &schema.Table{
		Name:       "prompt_appends",
		Columns:    PromptAppendsColumns,
		PrimaryKey: []*schema.Column{PromptAppendsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "promptappend_session_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{PromptAppendsColumns[1], PromptAppendsColumns[7]},
			},
			{
				Name:    "promptappend_session_id_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{PromptAppendsColumns[1], PromptAppendsColumns[4], PromptAppendsColumns[7]},
			},
		},
	}
	// QuestionBatchesColumns holds the columns for the "question_batches" table.
	QuestionBatchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "session_id", Type: field.TypeString},
		{Name: "origin_process_run_id", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString},
		{Name: "delivery_status", Type: field.TypeString, Default: "none"},
		{Name: "delivery_process_run_id", Type: field.TypeString, Default: ""},
		{Name: "questions", Type: field.TypeJSON},
		{Name: "answers", Type: field.TypeJSON},
		{Name: "cancel_reason", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "answered_at", Type: field.TypeTime, Nullable: true},
		{Name: "delivered_at", Type: field.TypeTime, Nullable: true},
	}
	// QuestionBatchesTable holds the schema information for the "question_batches" table.
	QuestionBatchesTable = &schema.Table{
		Name:       "question_batches",
		Columns:    QuestionBatchesColumns,
		PrimaryKey: []*schema.Column{QuestionBatchesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "questionbatch_session_id_status",
				Unique:  false,
				Columns: []*schema.Column{QuestionBatchesColumns[1], QuestionBatchesColumns[3]},
			},
			{
				Name:    "questionbatch_session_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{QuestionBatchesColumns[1], QuestionBatchesColumns[9]},
			},
			{
				Name:    "questionbatch_origin_process_run_id_status",
				Unique:  false,
				Columns: []*schema.Column{QuestionBatchesColumns[2], QuestionBatchesColumns[3]},
			},
			{
				Name:    "questionbatch_session_id_delivery_status",
				Unique:  false,
				Columns: []*schema.Column{QuestionBatchesColumns[1], QuestionBatchesColumns[4]},
			},
			{
				Name:    "questionbatch_delivery_process_run_id",
				Unique:  false,
				Columns: []*schema.Column{QuestionBatchesColumns[5]},
			},
		},
	}
	// QuickCommandsColumns holds the columns for the "quick_commands" table.
	QuickCommandsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// QuickCommandsTable holds the schema information for the "quick_commands" table.
	QuickCommandsTable = &schema.Table{
		Name:       "quick_commands",
		Columns:    QuickCommandsColumns,
		PrimaryKey: []*schema.Column{QuickCommandsColumns[0]},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "project_id", Type: field.TypeString},
		{Name: "requirement", Type: field.TypeString, Default: ""},
		{Name: "mode", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "priority", Type: field.TypeString, Default: "medium"},
		{Name: "close_reason", Type: field.TypeString, Nullable: true},
		{Name: "base_branch", Type: field.TypeString, Default: ""},
		{Name: "worktree_path", Type: field.TypeString, Default: ""},
		{Name: "worktree_branch", Type: field.TypeString, Default: ""},
		{Name: "worktree_base_commit", Type: field.TypeString, Default: ""},
		{Name: "worktree_head_commit", Type: field.TypeString, Default: ""},
		{Name: "worktree_cleanup_status", Type: field.TypeString, Default: "not_applicable"},
		{Name: "worktree_cleanup_attempts", Type: field.TypeInt, Default: 0},
		{Name: "worktree_ownership_token", Type: field.TypeString, Default: ""},
		{Name: "worktree_ownership_confirmed_at", Type: field.TypeTime, Nullable: true},
		{Name: "worktree_cleanup_requested_at", Type: field.TypeTime, Nullable: true},
		{Name: "worktree_cleanup_last_at", Type: field.TypeTime, Nullable: true},
		{Name: "worktree_cleanup_next_at", Type: field.TypeTime, Nullable: true},
		{Name: "worktree_cleanup_completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "worktree_cleanup_error_code", Type: field.TypeString, Default: ""},
		{Name: "worktree_cleanup_error", Type: field.TypeString, Default: ""},
		{Name: "worktree_cleanup_retryable", Type: field.TypeBool, Default: false},
		{Name: "codex_session_id", Type: field.TypeString, Default: ""},
		{Name: "codex_model", Type: field.TypeString, Default: ""},
		{Name: "reasoning_effort", Type: field.TypeString, Default: ""},
		{Name: "permission_mode", Type: field.TypeString, Default: ""},
		{Name: "fast_mode", Type: field.TypeBool, Default: false},
		{Name: "todo_list", Type: field.TypeJSON, Nullable: true},
		{Name: "usage", Type: field.TypeJSON, Nullable: true},
		{Name: "artifact_count", Type: field.TypeInt, Default: 0},
		{Name: "files_changed", Type: field.TypeInt, Default: 0},
		{Name: "queued_at", Type: field.TypeTime, Nullable: true},
		{Name: "queue_kind", Type: field.TypeString, Default: ""},
		{Name: "queue_priority", Type: field.TypeString, Default: "medium"},
		{Name: "queue_initial_start", Type: field.TypeBool, Nullable: true},
		{Name: "queue_review_after_reuse_failure", Type: field.TypeBool, Default: false},
		{Name: "queue_node_run_id", Type: field.TypeString, Default: ""},
		{Name: "queue_prompt", Type: field.TypeString, Default: ""},
		{Name: "queue_resume_codex_session_id", Type: field.TypeString, Default: ""},
		{Name: "queue_resume_of_process_run_id", Type: field.TypeString, Default: ""},
		{Name: "queue_answer_batch_id", Type: field.TypeString, Default: ""},
		{Name: "workflow_definition_id", Type: field.TypeString, Default: ""},
		{Name: "workflow_status", Type: field.TypeString, Default: ""},
		{Name: "workflow_current_node_id", Type: field.TypeString, Default: ""},
		{Name: "workflow_context", Type: field.TypeJSON},
		{Name: "workflow_pending_approval", Type: field.TypeJSON},
		{Name: "workflow_started_at", Type: field.TypeTime, Nullable: true},
		{Name: "workflow_stopped_at", Type: field.TypeTime, Nullable: true},
		{Name: "applied_system_commands", Type: field.TypeJSON, Nullable: true},
		{Name: "last_run_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "closed_at", Type: field.TypeTime, Nullable: true},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "session_project_id",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[1]},
			},
			{
				Name:    "session_project_id_updated_at",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[1], SessionsColumns[52]},
			},
			{
				Name:    "session_project_id_last_run_at",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[1], SessionsColumns[50]},
			},
			{
				Name:    "session_status",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[4]},
			},
			{
				Name:    "session_status_queue_priority_priority_queued_at",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[4], SessionsColumns[34], SessionsColumns[5], SessionsColumns[32]},
			},
			{
				Name:    "session_worktree_cleanup_status_worktree_cleanup_next_at_updated_at",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[12], SessionsColumns[18], SessionsColumns[52]},
			},
		},
	}
	// StagedAttachmentsColumns holds the columns for the "staged_attachments" table.
	StagedAttachmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "owner_key_hash", Type: field.TypeString, Default: ""},
		{Name: "filename", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "mime_type", Type: field.TypeString, Default: "application/octet-stream"},
		{Name: "size", Type: field.TypeInt64, Default: 0},
		{Name: "previewable", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// StagedAttachmentsTable holds the schema information for the "staged_attachments" table.
	StagedAttachmentsTable = &schema.Table{
		Name:       "staged_attachments",
		Columns:    StagedAttachmentsColumns,
		PrimaryKey: []*schema.Column{StagedAttachmentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "stagedattachment_owner_key_hash",
				Unique:  false,
				Columns: []*schema.Column{StagedAttachmentsColumns[1]},
			},
			{
				Name:    "stagedattachment_created_at",
				Unique:  false,
				Columns: []*schema.Column{StagedAttachmentsColumns[7]},
			},
		},
	}
	// SystemConfigurationsColumns holds the columns for the "system_configurations" table.
	SystemConfigurationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "wallpaper_color_scheme", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SystemConfigurationsTable holds the schema information for the "system_configurations" table.
	SystemConfigurationsTable = &schema.Table{
		Name:       "system_configurations",
		Columns:    SystemConfigurationsColumns,
		PrimaryKey: []*schema.Column{SystemConfigurationsColumns[0]},
	}
	// WorkflowDefinitionsColumns holds the columns for the "workflow_definitions" table.
	WorkflowDefinitionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "project_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "graph", Type: field.TypeJSON},
		{Name: "active", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// WorkflowDefinitionsTable holds the schema information for the "workflow_definitions" table.
	WorkflowDefinitionsTable = &schema.Table{
		Name:       "workflow_definitions",
		Columns:    WorkflowDefinitionsColumns,
		PrimaryKey: []*schema.Column{WorkflowDefinitionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "workflowdefinition_project_id_active",
				Unique:  false,
				Columns: []*schema.Column{WorkflowDefinitionsColumns[1], WorkflowDefinitionsColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventRecordsTable,
		MergeRecordsTable,
		NodeRunsTable,
		ProcessRunsTable,
		ProjectsTable,
		PromptAppendsTable,
		QuestionBatchesTable,
		QuickCommandsTable,
		SessionsTable,
		StagedAttachmentsTable,
		SystemConfigurationsTable,
		WorkflowDefinitionsTable,
	}
)

func init() {
}
