// Code generated by ent, DO NOT EDIT.

package mindmaptask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldContainsFold(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldProjectID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldSessionID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldStatus, v))
}

// ProcessRunID applies equality check predicate on the "process_run_id" field. It's identical to ProcessRunIDEQ.
func ProcessRunID(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldProcessRunID, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldAttempts, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldCreatedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldFinishedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldContainsFold(FieldProjectID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldContainsFold(FieldSessionID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldContainsFold(FieldStatus, v))
}

// ProcessRunIDEQ applies the EQ predicate on the "process_run_id" field.
func ProcessRunIDEQ(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldProcessRunID, v))
}

// ProcessRunIDNEQ applies the NEQ predicate on the "process_run_id" field.
func ProcessRunIDNEQ(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNEQ(FieldProcessRunID, v))
}

// ProcessRunIDIn applies the In predicate on the "process_run_id" field.
func ProcessRunIDIn(vs ...string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIn(FieldProcessRunID, vs...))
}

// ProcessRunIDNotIn applies the NotIn predicate on the "process_run_id" field.
func ProcessRunIDNotIn(vs ...string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotIn(FieldProcessRunID, vs...))
}

// ProcessRunIDGT applies the GT predicate on the "process_run_id" field.
func ProcessRunIDGT(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGT(FieldProcessRunID, v))
}

// ProcessRunIDGTE applies the GTE predicate on the "process_run_id" field.
func ProcessRunIDGTE(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGTE(FieldProcessRunID, v))
}

// ProcessRunIDLT applies the LT predicate on the "process_run_id" field.
func ProcessRunIDLT(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLT(FieldProcessRunID, v))
}

// ProcessRunIDLTE applies the LTE predicate on the "process_run_id" field.
func ProcessRunIDLTE(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLTE(FieldProcessRunID, v))
}

// ProcessRunIDContains applies the Contains predicate on the "process_run_id" field.
func ProcessRunIDContains(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldContains(FieldProcessRunID, v))
}

// ProcessRunIDHasPrefix applies the HasPrefix predicate on the "process_run_id" field.
func ProcessRunIDHasPrefix(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldHasPrefix(FieldProcessRunID, v))
}

// ProcessRunIDHasSuffix applies the HasSuffix predicate on the "process_run_id" field.
func ProcessRunIDHasSuffix(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldHasSuffix(FieldProcessRunID, v))
}

// ProcessRunIDEqualFold applies the EqualFold predicate on the "process_run_id" field.
func ProcessRunIDEqualFold(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEqualFold(FieldProcessRunID, v))
}

// ProcessRunIDContainsFold applies the ContainsFold predicate on the "process_run_id" field.
func ProcessRunIDContainsFold(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldContainsFold(FieldProcessRunID, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLTE(FieldAttempts, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldHasSuffix(FieldError, v))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldContainsFold(FieldError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLTE(FieldCreatedAt, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotNull(FieldFinishedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MindMapTask {
	return predicate.MindMapTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MindMapTask) predicate.MindMapTask {
	return predicate.MindMapTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MindMapTask) predicate.MindMapTask {
	return predicate.MindMapTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MindMapTask) predicate.MindMapTask {
	return predicate.MindMapTask(sql.NotPredicates(p))
}
