// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nzlov/anycode/internal/domain/mcp"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/mcpentry"
)

// MCPEntry is the model entity for the MCPEntry schema.
type MCPEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ScopeKind holds the value of the "scope_kind" field.
	ScopeKind string `json:"scope_kind,omitempty"`
	// ScopeID holds the value of the "scope_id" field.
	ScopeID string `json:"scope_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Definition holds the value of the "definition" field.
	Definition *mcp.Definition `json:"definition,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled      *bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MCPEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mcpentry.FieldDefinition:
			values[i] = new([]byte)
		case mcpentry.FieldEnabled:
			values[i] = new(sql.NullBool)
		case mcpentry.FieldID, mcpentry.FieldScopeKind, mcpentry.FieldScopeID, mcpentry.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MCPEntry fields.
func (_m *MCPEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mcpentry.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case mcpentry.FieldScopeKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_kind", values[i])
			} else if value.Valid {
				_m.ScopeKind = value.String
			}
		case mcpentry.FieldScopeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_id", values[i])
			} else if value.Valid {
				_m.ScopeID = value.String
			}
		case mcpentry.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case mcpentry.FieldDefinition:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field definition", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Definition); err != nil {
					return fmt.Errorf("unmarshal field definition: %w", err)
				}
			}
		case mcpentry.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = new(bool)
				*_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MCPEntry.
// This includes values selected through modifiers, order, etc.
func (_m *MCPEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MCPEntry.
// Note that you need to call MCPEntry.Unwrap() before calling this method if this MCPEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MCPEntry) Update() *MCPEntryUpdateOne {
	return NewMCPEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MCPEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MCPEntry) Unwrap() *MCPEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MCPEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MCPEntry) String() string {
	var builder strings.Builder
	builder.WriteString("MCPEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("scope_kind=")
	builder.WriteString(_m.ScopeKind)
	builder.WriteString(", ")
	builder.WriteString("scope_id=")
	builder.WriteString(_m.ScopeID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("definition=")
	builder.WriteString(fmt.Sprintf("%v", _m.Definition))
	builder.WriteString(", ")
	if v := _m.Enabled; v != nil {
		builder.WriteString("enabled=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MCPEntries is a parsable slice of MCPEntry.
type MCPEntries []*MCPEntry
