// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/mergerecord"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/predicate"
)

// MergeRecordUpdate is the builder for updating MergeRecord entities.
type MergeRecordUpdate struct {
	config
	hooks    []Hook
	mutation *MergeRecordMutation
}

// Where appends a list predicates to the MergeRecordUpdate builder.
func (_u *MergeRecordUpdate) Where(ps ...predicate.MergeRecord) *MergeRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MergeRecordUpdate) SetSessionID(v string) *MergeRecordUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MergeRecordUpdate) SetNillableSessionID(v *string) *MergeRecordUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetNodeRunID sets the "node_run_id" field.
func (_u *MergeRecordUpdate) SetNodeRunID(v string) *MergeRecordUpdate {
	_u.mutation.SetNodeRunID(v)
	return _u
}

// SetNillableNodeRunID sets the "node_run_id" field if the given value is not nil.
func (_u *MergeRecordUpdate) SetNillableNodeRunID(v *string) *MergeRecordUpdate {
	if v != nil {
		_u.SetNodeRunID(*v)
	}
	return _u
}

// ClearNodeRunID clears the value of the "node_run_id" field.
func (_u *MergeRecordUpdate) ClearNodeRunID() *MergeRecordUpdate {
	_u.mutation.ClearNodeRunID()
	return _u
}

// SetStrategy sets the "strategy" field.
func (_u *MergeRecordUpdate) SetStrategy(v string) *MergeRecordUpdate {
	_u.mutation.SetStrategy(v)
	return _u
}

// SetNillableStrategy sets the "strategy" field if the given value is not nil.
func (_u *MergeRecordUpdate) SetNillableStrategy(v *string) *MergeRecordUpdate {
	if v != nil {
		_u.SetStrategy(*v)
	}
	return _u
}

// SetBaseBranch sets the "base_branch" field.
func (_u *MergeRecordUpdate) SetBaseBranch(v string) *MergeRecordUpdate {
	_u.mutation.SetBaseBranch(v)
	return _u
}

// SetNillableBaseBranch sets the "base_branch" field if the given value is not nil.
func (_u *MergeRecordUpdate) SetNillableBaseBranch(v *string) *MergeRecordUpdate {
	if v != nil {
		_u.SetBaseBranch(*v)
	}
	return _u
}

// SetWorktreeBranch sets the "worktree_branch" field.
func (_u *MergeRecordUpdate) SetWorktreeBranch(v string) *MergeRecordUpdate {
	_u.mutation.SetWorktreeBranch(v)
	return _u
}

// SetNillableWorktreeBranch sets the "worktree_branch" field if the given value is not nil.
func (_u *MergeRecordUpdate) SetNillableWorktreeBranch(v *string) *MergeRecordUpdate {
	if v != nil {
		_u.SetWorktreeBranch(*v)
	}
	return _u
}

// SetBaseCommit sets the "base_commit" field.
func (_u *MergeRecordUpdate) SetBaseCommit(v string) *MergeRecordUpdate {
	_u.mutation.SetBaseCommit(v)
	return _u
}

// SetNillableBaseCommit sets the "base_commit" field if the given value is not nil.
func (_u *MergeRecordUpdate) SetNillableBaseCommit(v *string) *MergeRecordUpdate {
	if v != nil {
		_u.SetBaseCommit(*v)
	}
	return _u
}

// SetHeadCommit sets the "head_commit" field.
func (_u *MergeRecordUpdate) SetHeadCommit(v string) *MergeRecordUpdate {
	_u.mutation.SetHeadCommit(v)
	return _u
}

// SetNillableHeadCommit sets the "head_commit" field if the given value is not nil.
func (_u *MergeRecordUpdate) SetNillableHeadCommit(v *string) *MergeRecordUpdate {
	if v != nil {
		_u.SetHeadCommit(*v)
	}
	return _u
}

// SetMergeCommit sets the "merge_commit" field.
func (_u *MergeRecordUpdate) SetMergeCommit(v string) *MergeRecordUpdate {
	_u.mutation.SetMergeCommit(v)
	return _u
}

// SetNillableMergeCommit sets the "merge_commit" field if the given value is not nil.
func (_u *MergeRecordUpdate) SetNillableMergeCommit(v *string) *MergeRecordUpdate {
	if v != nil {
		_u.SetMergeCommit(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MergeRecordUpdate) SetStatus(v string) *MergeRecordUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MergeRecordUpdate) SetNillableStatus(v *string) *MergeRecordUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *MergeRecordUpdate) SetFailureCode(v string) *MergeRecordUpdate {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *MergeRecordUpdate) SetNillableFailureCode(v *string) *MergeRecordUpdate {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *MergeRecordUpdate) SetFailureReason(v string) *MergeRecordUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *MergeRecordUpdate) SetNillableFailureReason(v *string) *MergeRecordUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// SetMergedAt sets the "merged_at" field.
func (_u *MergeRecordUpdate) SetMergedAt(v time.Time) *MergeRecordUpdate {
	_u.mutation.SetMergedAt(v)
	return _u
}

// SetNillableMergedAt sets the "merged_at" field if the given value is not nil.
func (_u *MergeRecordUpdate) SetNillableMergedAt(v *time.Time) *MergeRecordUpdate {
	if v != nil {
		_u.SetMergedAt(*v)
	}
	return _u
}

// ClearMergedAt clears the value of the "merged_at" field.
func (_u *MergeRecordUpdate) ClearMergedAt() *MergeRecordUpdate {
	_u.mutation.ClearMergedAt()
	return _u
}

// Mutation returns the MergeRecordMutation object of the builder.
func (_u *MergeRecordUpdate) Mutation() *MergeRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MergeRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MergeRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MergeRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MergeRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MergeRecordUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := mergerecord.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "MergeRecord.session_id": %w`, err)}
		}
	}
	return nil
}

func (_u *MergeRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mergerecord.Table, mergerecord.Columns, sqlgraph.NewFieldSpec(mergerecord.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(mergerecord.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeRunID(); ok {
		_spec.SetField(mergerecord.FieldNodeRunID, field.TypeString, value)
	}
	if _u.mutation.NodeRunIDCleared() {
		_spec.ClearField(mergerecord.FieldNodeRunID, field.TypeString)
	}
	if value, ok := _u.mutation.Strategy(); ok {
		_spec.SetField(mergerecord.FieldStrategy, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseBranch(); ok {
		_spec.SetField(mergerecord.FieldBaseBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorktreeBranch(); ok {
		_spec.SetField(mergerecord.FieldWorktreeBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseCommit(); ok {
		_spec.SetField(mergerecord.FieldBaseCommit, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeadCommit(); ok {
		_spec.SetField(mergerecord.FieldHeadCommit, field.TypeString, value)
	}
	if value, ok := _u.mutation.MergeCommit(); ok {
		_spec.SetField(mergerecord.FieldMergeCommit, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mergerecord.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(mergerecord.FieldFailureCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(mergerecord.FieldFailureReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.MergedAt(); ok {
		_spec.SetField(mergerecord.FieldMergedAt, field.TypeTime, value)
	}
	if _u.mutation.MergedAtCleared() {
		_spec.ClearField(mergerecord.FieldMergedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mergerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MergeRecordUpdateOne is the builder for updating a single MergeRecord entity.
type MergeRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MergeRecordMutation
}

// SetSessionID sets the "session_id" field.
func (_u *MergeRecordUpdateOne) SetSessionID(v string) *MergeRecordUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MergeRecordUpdateOne) SetNillableSessionID(v *string) *MergeRecordUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetNodeRunID sets the "node_run_id" field.
func (_u *MergeRecordUpdateOne) SetNodeRunID(v string) *MergeRecordUpdateOne {
	_u.mutation.SetNodeRunID(v)
	return _u
}

// SetNillableNodeRunID sets the "node_run_id" field if the given value is not nil.
func (_u *MergeRecordUpdateOne) SetNillableNodeRunID(v *string) *MergeRecordUpdateOne {
	if v != nil {
		_u.SetNodeRunID(*v)
	}
	return _u
}

// ClearNodeRunID clears the value of the "node_run_id" field.
func (_u *MergeRecordUpdateOne) ClearNodeRunID() *MergeRecordUpdateOne {
	_u.mutation.ClearNodeRunID()
	return _u
}

// SetStrategy sets the "strategy" field.
func (_u *MergeRecordUpdateOne) SetStrategy(v string) *MergeRecordUpdateOne {
	_u.mutation.SetStrategy(v)
	return _u
}

// SetNillableStrategy sets the "strategy" field if the given value is not nil.
func (_u *MergeRecordUpdateOne) SetNillableStrategy(v *string) *MergeRecordUpdateOne {
	if v != nil {
		_u.SetStrategy(*v)
	}
	return _u
}

// SetBaseBranch sets the "base_branch" field.
func (_u *MergeRecordUpdateOne) SetBaseBranch(v string) *MergeRecordUpdateOne {
	_u.mutation.SetBaseBranch(v)
	return _u
}

// SetNillableBaseBranch sets the "base_branch" field if the given value is not nil.
func (_u *MergeRecordUpdateOne) SetNillableBaseBranch(v *string) *MergeRecordUpdateOne {
	if v != nil {
		_u.SetBaseBranch(*v)
	}
	return _u
}

// SetWorktreeBranch sets the "worktree_branch" field.
func (_u *MergeRecordUpdateOne) SetWorktreeBranch(v string) *MergeRecordUpdateOne {
	_u.mutation.SetWorktreeBranch(v)
	return _u
}

// SetNillableWorktreeBranch sets the "worktree_branch" field if the given value is not nil.
func (_u *MergeRecordUpdateOne) SetNillableWorktreeBranch(v *string) *MergeRecordUpdateOne {
	if v != nil {
		_u.SetWorktreeBranch(*v)
	}
	return _u
}

// SetBaseCommit sets the "base_commit" field.
func (_u *MergeRecordUpdateOne) SetBaseCommit(v string) *MergeRecordUpdateOne {
	_u.mutation.SetBaseCommit(v)
	return _u
}

// SetNillableBaseCommit sets the "base_commit" field if the given value is not nil.
func (_u *MergeRecordUpdateOne) SetNillableBaseCommit(v *string) *MergeRecordUpdateOne {
	if v != nil {
		_u.SetBaseCommit(*v)
	}
	return _u
}

// SetHeadCommit sets the "head_commit" field.
func (_u *MergeRecordUpdateOne) SetHeadCommit(v string) *MergeRecordUpdateOne {
	_u.mutation.SetHeadCommit(v)
	return _u
}

// SetNillableHeadCommit sets the "head_commit" field if the given value is not nil.
func (_u *MergeRecordUpdateOne) SetNillableHeadCommit(v *string) *MergeRecordUpdateOne {
	if v != nil {
		_u.SetHeadCommit(*v)
	}
	return _u
}

// SetMergeCommit sets the "merge_commit" field.
func (_u *MergeRecordUpdateOne) SetMergeCommit(v string) *MergeRecordUpdateOne {
	_u.mutation.SetMergeCommit(v)
	return _u
}

// SetNillableMergeCommit sets the "merge_commit" field if the given value is not nil.
func (_u *MergeRecordUpdateOne) SetNillableMergeCommit(v *string) *MergeRecordUpdateOne {
	if v != nil {
		_u.SetMergeCommit(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MergeRecordUpdateOne) SetStatus(v string) *MergeRecordUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MergeRecordUpdateOne) SetNillableStatus(v *string) *MergeRecordUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *MergeRecordUpdateOne) SetFailureCode(v string) *MergeRecordUpdateOne {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *MergeRecordUpdateOne) SetNillableFailureCode(v *string) *MergeRecordUpdateOne {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *MergeRecordUpdateOne) SetFailureReason(v string) *MergeRecordUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *MergeRecordUpdateOne) SetNillableFailureReason(v *string) *MergeRecordUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// SetMergedAt sets the "merged_at" field.
func (_u *MergeRecordUpdateOne) SetMergedAt(v time.Time) *MergeRecordUpdateOne {
	_u.mutation.SetMergedAt(v)
	return _u
}

// SetNillableMergedAt sets the "merged_at" field if the given value is not nil.
func (_u *MergeRecordUpdateOne) SetNillableMergedAt(v *time.Time) *MergeRecordUpdateOne {
	if v != nil {
		_u.SetMergedAt(*v)
	}
	return _u
}

// ClearMergedAt clears the value of the "merged_at" field.
func (_u *MergeRecordUpdateOne) ClearMergedAt() *MergeRecordUpdateOne {
	_u.mutation.ClearMergedAt()
	return _u
}

// Mutation returns the MergeRecordMutation object of the builder.
func (_u *MergeRecordUpdateOne) Mutation() *MergeRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the MergeRecordUpdate builder.
func (_u *MergeRecordUpdateOne) Where(ps ...predicate.MergeRecord) *MergeRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MergeRecordUpdateOne) Select(field string, fields ...string) *MergeRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MergeRecord entity.
func (_u *MergeRecordUpdateOne) Save(ctx context.Context) (*MergeRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MergeRecordUpdateOne) SaveX(ctx context.Context) *MergeRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MergeRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MergeRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MergeRecordUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := mergerecord.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "MergeRecord.session_id": %w`, err)}
		}
	}
	return nil
}

func (_u *MergeRecordUpdateOne) sqlSave(ctx context.Context) (_node *MergeRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mergerecord.Table, mergerecord.Columns, sqlgraph.NewFieldSpec(mergerecord.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MergeRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mergerecord.FieldID)
		for _, f := range fields {
			if !mergerecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mergerecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(mergerecord.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeRunID(); ok {
		_spec.SetField(mergerecord.FieldNodeRunID, field.TypeString, value)
	}
	if _u.mutation.NodeRunIDCleared() {
		_spec.ClearField(mergerecord.FieldNodeRunID, field.TypeString)
	}
	if value, ok := _u.mutation.Strategy(); ok {
		_spec.SetField(mergerecord.FieldStrategy, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseBranch(); ok {
		_spec.SetField(mergerecord.FieldBaseBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorktreeBranch(); ok {
		_spec.SetField(mergerecord.FieldWorktreeBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseCommit(); ok {
		_spec.SetField(mergerecord.FieldBaseCommit, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeadCommit(); ok {
		_spec.SetField(mergerecord.FieldHeadCommit, field.TypeString, value)
	}
	if value, ok := _u.mutation.MergeCommit(); ok {
		_spec.SetField(mergerecord.FieldMergeCommit, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mergerecord.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(mergerecord.FieldFailureCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(mergerecord.FieldFailureReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.MergedAt(); ok {
		_spec.SetField(mergerecord.FieldMergedAt, field.TypeTime, value)
	}
	if _u.mutation.MergedAtCleared() {
		_spec.ClearField(mergerecord.FieldMergedAt, field.TypeTime)
	}
	_node = &MergeRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mergerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
