// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/mindmaptask"
)

// MindMapTaskCreate is the builder for creating a MindMapTask entity.
type MindMapTaskCreate struct {
	config
	mutation *MindMapTaskMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *MindMapTaskCreate) SetProjectID(v string) *MindMapTaskCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *MindMapTaskCreate) SetSessionID(v string) *MindMapTaskCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MindMapTaskCreate) SetStatus(v string) *MindMapTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetProcessRunID sets the "process_run_id" field.
func (_c *MindMapTaskCreate) SetProcessRunID(v string) *MindMapTaskCreate {
	_c.mutation.SetProcessRunID(v)
	return _c
}

// SetNillableProcessRunID sets the "process_run_id" field if the given value is not nil.
func (_c *MindMapTaskCreate) SetNillableProcessRunID(v *string) *MindMapTaskCreate {
	if v != nil {
		_c.SetProcessRunID(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *MindMapTaskCreate) SetAttempts(v int) *MindMapTaskCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *MindMapTaskCreate) SetNillableAttempts(v *int) *MindMapTaskCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *MindMapTaskCreate) SetError(v string) *MindMapTaskCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *MindMapTaskCreate) SetNillableError(v *string) *MindMapTaskCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MindMapTaskCreate) SetCreatedAt(v time.Time) *MindMapTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MindMapTaskCreate) SetNillableCreatedAt(v *time.Time) *MindMapTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *MindMapTaskCreate) SetStartedAt(v time.Time) *MindMapTaskCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *MindMapTaskCreate) SetNillableStartedAt(v *time.Time) *MindMapTaskCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *MindMapTaskCreate) SetFinishedAt(v time.Time) *MindMapTaskCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *MindMapTaskCreate) SetNillableFinishedAt(v *time.Time) *MindMapTaskCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MindMapTaskCreate) SetUpdatedAt(v time.Time) *MindMapTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MindMapTaskCreate) SetNillableUpdatedAt(v *time.Time) *MindMapTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MindMapTaskCreate) SetID(v string) *MindMapTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MindMapTaskMutation object of the builder.
func (_c *MindMapTaskCreate) Mutation() *MindMapTaskMutation {
	return _c.mutation
}

// Save creates the MindMapTask in the database.
func (_c *MindMapTaskCreate) Save(ctx context.Context) (*MindMapTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MindMapTaskCreate) SaveX(ctx context.Context) *MindMapTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MindMapTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MindMapTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MindMapTaskCreate) defaults() {
	if _, ok := _c.mutation.ProcessRunID(); !ok {
		v := mindmaptask.DefaultProcessRunID
		_c.mutation.SetProcessRunID(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := mindmaptask.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.Error(); !ok {
		v := mindmaptask.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mindmaptask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mindmaptask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MindMapTaskCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "MindMapTask.project_id"`)}
	}
	if v, ok := _c.mutation.ProjectID(); ok {
		if err := mindmaptask.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "MindMapTask.project_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "MindMapTask.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := mindmaptask.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "MindMapTask.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MindMapTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := mindmaptask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MindMapTask.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProcessRunID(); !ok {
		return &ValidationError{Name: "process_run_id", err: errors.New(`ent: missing required field "MindMapTask.process_run_id"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "MindMapTask.attempts"`)}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`ent: missing required field "MindMapTask.error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MindMapTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MindMapTask.updated_at"`)}
	}
	return nil
}

func (_c *MindMapTaskCreate) sqlSave(ctx context.Context) (*MindMapTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected MindMapTask.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MindMapTaskCreate) createSpec() (*MindMapTask, *sqlgraph.CreateSpec) {
	var (
		_node = &MindMapTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mindmaptask.Table, sqlgraph.NewFieldSpec(mindmaptask.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(mindmaptask.FieldProjectID, field.TypeString, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(mindmaptask.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(mindmaptask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProcessRunID(); ok {
		_spec.SetField(mindmaptask.FieldProcessRunID, field.TypeString, value)
		_node.ProcessRunID = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(mindmaptask.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(mindmaptask.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mindmaptask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(mindmaptask.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(mindmaptask.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mindmaptask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// MindMapTaskCreateBulk is the builder for creating many MindMapTask entities in bulk.
type MindMapTaskCreateBulk struct {
	config
	err      error
	builders []*MindMapTaskCreate
}

// Save creates the MindMapTask entities in the database.
func (_c *MindMapTaskCreateBulk) Save(ctx context.Context) ([]*MindMapTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MindMapTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MindMapTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MindMapTaskCreateBulk) SaveX(ctx context.Context) []*MindMapTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MindMapTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MindMapTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
