// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/mindmapnode"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/schema"
)

// MindMapNode is the model entity for the MindMapNode schema.
type MindMapNode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID string `json:"project_id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID string `json:"node_id,omitempty"`
	// Title holds the value of the "title" field.
	Title *string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content *string `json:"content,omitempty"`
	// Files holds the value of the "files" field.
	Files []schema.MindMapNodeFile `json:"files,omitempty"`
	// TitleUpdatedAt holds the value of the "title_updated_at" field.
	TitleUpdatedAt *time.Time `json:"title_updated_at,omitempty"`
	// ContentUpdatedAt holds the value of the "content_updated_at" field.
	ContentUpdatedAt *time.Time `json:"content_updated_at,omitempty"`
	// FilesUpdatedAt holds the value of the "files_updated_at" field.
	FilesUpdatedAt *time.Time `json:"files_updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt    *time.Time `json:"deleted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MindMapNode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mindmapnode.FieldFiles:
			values[i] = new([]byte)
		case mindmapnode.FieldID:
			values[i] = new(sql.NullInt64)
		case mindmapnode.FieldProjectID, mindmapnode.FieldSessionID, mindmapnode.FieldNodeID, mindmapnode.FieldTitle, mindmapnode.FieldContent:
			values[i] = new(sql.NullString)
		case mindmapnode.FieldTitleUpdatedAt, mindmapnode.FieldContentUpdatedAt, mindmapnode.FieldFilesUpdatedAt, mindmapnode.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MindMapNode fields.
func (_m *MindMapNode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mindmapnode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case mindmapnode.FieldProjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = value.String
			}
		case mindmapnode.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case mindmapnode.FieldNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = value.String
			}
		case mindmapnode.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = new(string)
				*_m.Title = value.String
			}
		case mindmapnode.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = new(string)
				*_m.Content = value.String
			}
		case mindmapnode.FieldFiles:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field files", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Files); err != nil {
					return fmt.Errorf("unmarshal field files: %w", err)
				}
			}
		case mindmapnode.FieldTitleUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field title_updated_at", values[i])
			} else if value.Valid {
				_m.TitleUpdatedAt = new(time.Time)
				*_m.TitleUpdatedAt = value.Time
			}
		case mindmapnode.FieldContentUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field content_updated_at", values[i])
			} else if value.Valid {
				_m.ContentUpdatedAt = new(time.Time)
				*_m.ContentUpdatedAt = value.Time
			}
		case mindmapnode.FieldFilesUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field files_updated_at", values[i])
			} else if value.Valid {
				_m.FilesUpdatedAt = new(time.Time)
				*_m.FilesUpdatedAt = value.Time
			}
		case mindmapnode.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MindMapNode.
// This includes values selected through modifiers, order, etc.
func (_m *MindMapNode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MindMapNode.
// Note that you need to call MindMapNode.Unwrap() before calling this method if this MindMapNode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MindMapNode) Update() *MindMapNodeUpdateOne {
	return NewMindMapNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MindMapNode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MindMapNode) Unwrap() *MindMapNode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MindMapNode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MindMapNode) String() string {
	var builder strings.Builder
	builder.WriteString("MindMapNode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(_m.ProjectID)
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("node_id=")
	builder.WriteString(_m.NodeID)
	builder.WriteString(", ")
	if v := _m.Title; v != nil {
		builder.WriteString("title=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Content; v != nil {
		builder.WriteString("content=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("files=")
	builder.WriteString(fmt.Sprintf("%v", _m.Files))
	builder.WriteString(", ")
	if v := _m.TitleUpdatedAt; v != nil {
		builder.WriteString("title_updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ContentUpdatedAt; v != nil {
		builder.WriteString("content_updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FilesUpdatedAt; v != nil {
		builder.WriteString("files_updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// MindMapNodes is a parsable slice of MindMapNode.
type MindMapNodes []*MindMapNode
