// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/mindmapnode"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/predicate"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/schema"
)

// MindMapNodeUpdate is the builder for updating MindMapNode entities.
type MindMapNodeUpdate struct {
	config
	hooks    []Hook
	mutation *MindMapNodeMutation
}

// Where appends a list predicates to the MindMapNodeUpdate builder.
func (_u *MindMapNodeUpdate) Where(ps ...predicate.MindMapNode) *MindMapNodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *MindMapNodeUpdate) SetProjectID(v string) *MindMapNodeUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *MindMapNodeUpdate) SetNillableProjectID(v *string) *MindMapNodeUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MindMapNodeUpdate) SetSessionID(v string) *MindMapNodeUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MindMapNodeUpdate) SetNillableSessionID(v *string) *MindMapNodeUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *MindMapNodeUpdate) SetNodeID(v string) *MindMapNodeUpdate {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *MindMapNodeUpdate) SetNillableNodeID(v *string) *MindMapNodeUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *MindMapNodeUpdate) SetTitle(v string) *MindMapNodeUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MindMapNodeUpdate) SetNillableTitle(v *string) *MindMapNodeUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *MindMapNodeUpdate) ClearTitle() *MindMapNodeUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetContent sets the "content" field.
func (_u *MindMapNodeUpdate) SetContent(v string) *MindMapNodeUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MindMapNodeUpdate) SetNillableContent(v *string) *MindMapNodeUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *MindMapNodeUpdate) ClearContent() *MindMapNodeUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetFiles sets the "files" field.
func (_u *MindMapNodeUpdate) SetFiles(v []schema.MindMapNodeFile) *MindMapNodeUpdate {
	_u.mutation.SetFiles(v)
	return _u
}

// AppendFiles appends value to the "files" field.
func (_u *MindMapNodeUpdate) AppendFiles(v []schema.MindMapNodeFile) *MindMapNodeUpdate {
	_u.mutation.AppendFiles(v)
	return _u
}

// ClearFiles clears the value of the "files" field.
func (_u *MindMapNodeUpdate) ClearFiles() *MindMapNodeUpdate {
	_u.mutation.ClearFiles()
	return _u
}

// SetTitleUpdatedAt sets the "title_updated_at" field.
func (_u *MindMapNodeUpdate) SetTitleUpdatedAt(v time.Time) *MindMapNodeUpdate {
	_u.mutation.SetTitleUpdatedAt(v)
	return _u
}

// SetNillableTitleUpdatedAt sets the "title_updated_at" field if the given value is not nil.
func (_u *MindMapNodeUpdate) SetNillableTitleUpdatedAt(v *time.Time) *MindMapNodeUpdate {
	if v != nil {
		_u.SetTitleUpdatedAt(*v)
	}
	return _u
}

// ClearTitleUpdatedAt clears the value of the "title_updated_at" field.
func (_u *MindMapNodeUpdate) ClearTitleUpdatedAt() *MindMapNodeUpdate {
	_u.mutation.ClearTitleUpdatedAt()
	return _u
}

// SetContentUpdatedAt sets the "content_updated_at" field.
func (_u *MindMapNodeUpdate) SetContentUpdatedAt(v time.Time) *MindMapNodeUpdate {
	_u.mutation.SetContentUpdatedAt(v)
	return _u
}

// SetNillableContentUpdatedAt sets the "content_updated_at" field if the given value is not nil.
func (_u *MindMapNodeUpdate) SetNillableContentUpdatedAt(v *time.Time) *MindMapNodeUpdate {
	if v != nil {
		_u.SetContentUpdatedAt(*v)
	}
	return _u
}

// ClearContentUpdatedAt clears the value of the "content_updated_at" field.
func (_u *MindMapNodeUpdate) ClearContentUpdatedAt() *MindMapNodeUpdate {
	_u.mutation.ClearContentUpdatedAt()
	return _u
}

// SetFilesUpdatedAt sets the "files_updated_at" field.
func (_u *MindMapNodeUpdate) SetFilesUpdatedAt(v time.Time) *MindMapNodeUpdate {
	_u.mutation.SetFilesUpdatedAt(v)
	return _u
}

// SetNillableFilesUpdatedAt sets the "files_updated_at" field if the given value is not nil.
func (_u *MindMapNodeUpdate) SetNillableFilesUpdatedAt(v *time.Time) *MindMapNodeUpdate {
	if v != nil {
		_u.SetFilesUpdatedAt(*v)
	}
	return _u
}

// ClearFilesUpdatedAt clears the value of the "files_updated_at" field.
func (_u *MindMapNodeUpdate) ClearFilesUpdatedAt() *MindMapNodeUpdate {
	_u.mutation.ClearFilesUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MindMapNodeUpdate) SetDeletedAt(v time.Time) *MindMapNodeUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MindMapNodeUpdate) SetNillableDeletedAt(v *time.Time) *MindMapNodeUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MindMapNodeUpdate) ClearDeletedAt() *MindMapNodeUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the MindMapNodeMutation object of the builder.
func (_u *MindMapNodeUpdate) Mutation() *MindMapNodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MindMapNodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MindMapNodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MindMapNodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MindMapNodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MindMapNodeUpdate) check() error {
	if v, ok := _u.mutation.ProjectID(); ok {
		if err := mindmapnode.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "MindMapNode.project_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NodeID(); ok {
		if err := mindmapnode.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "MindMapNode.node_id": %w`, err)}
		}
	}
	return nil
}

func (_u *MindMapNodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mindmapnode.Table, mindmapnode.Columns, sqlgraph.NewFieldSpec(mindmapnode.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(mindmapnode.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(mindmapnode.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(mindmapnode.FieldNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(mindmapnode.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(mindmapnode.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(mindmapnode.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(mindmapnode.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Files(); ok {
		_spec.SetField(mindmapnode.FieldFiles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFiles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mindmapnode.FieldFiles, value)
		})
	}
	if _u.mutation.FilesCleared() {
		_spec.ClearField(mindmapnode.FieldFiles, field.TypeJSON)
	}
	if value, ok := _u.mutation.TitleUpdatedAt(); ok {
		_spec.SetField(mindmapnode.FieldTitleUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TitleUpdatedAtCleared() {
		_spec.ClearField(mindmapnode.FieldTitleUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ContentUpdatedAt(); ok {
		_spec.SetField(mindmapnode.FieldContentUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ContentUpdatedAtCleared() {
		_spec.ClearField(mindmapnode.FieldContentUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FilesUpdatedAt(); ok {
		_spec.SetField(mindmapnode.FieldFilesUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FilesUpdatedAtCleared() {
		_spec.ClearField(mindmapnode.FieldFilesUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mindmapnode.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mindmapnode.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mindmapnode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MindMapNodeUpdateOne is the builder for updating a single MindMapNode entity.
type MindMapNodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MindMapNodeMutation
}

// SetProjectID sets the "project_id" field.
func (_u *MindMapNodeUpdateOne) SetProjectID(v string) *MindMapNodeUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *MindMapNodeUpdateOne) SetNillableProjectID(v *string) *MindMapNodeUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MindMapNodeUpdateOne) SetSessionID(v string) *MindMapNodeUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MindMapNodeUpdateOne) SetNillableSessionID(v *string) *MindMapNodeUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *MindMapNodeUpdateOne) SetNodeID(v string) *MindMapNodeUpdateOne {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *MindMapNodeUpdateOne) SetNillableNodeID(v *string) *MindMapNodeUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *MindMapNodeUpdateOne) SetTitle(v string) *MindMapNodeUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MindMapNodeUpdateOne) SetNillableTitle(v *string) *MindMapNodeUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *MindMapNodeUpdateOne) ClearTitle() *MindMapNodeUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetContent sets the "content" field.
func (_u *MindMapNodeUpdateOne) SetContent(v string) *MindMapNodeUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MindMapNodeUpdateOne) SetNillableContent(v *string) *MindMapNodeUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *MindMapNodeUpdateOne) ClearContent() *MindMapNodeUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetFiles sets the "files" field.
func (_u *MindMapNodeUpdateOne) SetFiles(v []schema.MindMapNodeFile) *MindMapNodeUpdateOne {
	_u.mutation.SetFiles(v)
	return _u
}

// AppendFiles appends value to the "files" field.
func (_u *MindMapNodeUpdateOne) AppendFiles(v []schema.MindMapNodeFile) *MindMapNodeUpdateOne {
	_u.mutation.AppendFiles(v)
	return _u
}

// ClearFiles clears the value of the "files" field.
func (_u *MindMapNodeUpdateOne) ClearFiles() *MindMapNodeUpdateOne {
	_u.mutation.ClearFiles()
	return _u
}

// SetTitleUpdatedAt sets the "title_updated_at" field.
func (_u *MindMapNodeUpdateOne) SetTitleUpdatedAt(v time.Time) *MindMapNodeUpdateOne {
	_u.mutation.SetTitleUpdatedAt(v)
	return _u
}

// SetNillableTitleUpdatedAt sets the "title_updated_at" field if the given value is not nil.
func (_u *MindMapNodeUpdateOne) SetNillableTitleUpdatedAt(v *time.Time) *MindMapNodeUpdateOne {
	if v != nil {
		_u.SetTitleUpdatedAt(*v)
	}
	return _u
}

// ClearTitleUpdatedAt clears the value of the "title_updated_at" field.
func (_u *MindMapNodeUpdateOne) ClearTitleUpdatedAt() *MindMapNodeUpdateOne {
	_u.mutation.ClearTitleUpdatedAt()
	return _u
}

// SetContentUpdatedAt sets the "content_updated_at" field.
func (_u *MindMapNodeUpdateOne) SetContentUpdatedAt(v time.Time) *MindMapNodeUpdateOne {
	_u.mutation.SetContentUpdatedAt(v)
	return _u
}

// SetNillableContentUpdatedAt sets the "content_updated_at" field if the given value is not nil.
func (_u *MindMapNodeUpdateOne) SetNillableContentUpdatedAt(v *time.Time) *MindMapNodeUpdateOne {
	if v != nil {
		_u.SetContentUpdatedAt(*v)
	}
	return _u
}

// ClearContentUpdatedAt clears the value of the "content_updated_at" field.
func (_u *MindMapNodeUpdateOne) ClearContentUpdatedAt() *MindMapNodeUpdateOne {
	_u.mutation.ClearContentUpdatedAt()
	return _u
}

// SetFilesUpdatedAt sets the "files_updated_at" field.
func (_u *MindMapNodeUpdateOne) SetFilesUpdatedAt(v time.Time) *MindMapNodeUpdateOne {
	_u.mutation.SetFilesUpdatedAt(v)
	return _u
}

// SetNillableFilesUpdatedAt sets the "files_updated_at" field if the given value is not nil.
func (_u *MindMapNodeUpdateOne) SetNillableFilesUpdatedAt(v *time.Time) *MindMapNodeUpdateOne {
	if v != nil {
		_u.SetFilesUpdatedAt(*v)
	}
	return _u
}

// ClearFilesUpdatedAt clears the value of the "files_updated_at" field.
func (_u *MindMapNodeUpdateOne) ClearFilesUpdatedAt() *MindMapNodeUpdateOne {
	_u.mutation.ClearFilesUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MindMapNodeUpdateOne) SetDeletedAt(v time.Time) *MindMapNodeUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MindMapNodeUpdateOne) SetNillableDeletedAt(v *time.Time) *MindMapNodeUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MindMapNodeUpdateOne) ClearDeletedAt() *MindMapNodeUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the MindMapNodeMutation object of the builder.
func (_u *MindMapNodeUpdateOne) Mutation() *MindMapNodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the MindMapNodeUpdate builder.
func (_u *MindMapNodeUpdateOne) Where(ps ...predicate.MindMapNode) *MindMapNodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MindMapNodeUpdateOne) Select(field string, fields ...string) *MindMapNodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MindMapNode entity.
func (_u *MindMapNodeUpdateOne) Save(ctx context.Context) (*MindMapNode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MindMapNodeUpdateOne) SaveX(ctx context.Context) *MindMapNode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MindMapNodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MindMapNodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MindMapNodeUpdateOne) check() error {
	if v, ok := _u.mutation.ProjectID(); ok {
		if err := mindmapnode.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "MindMapNode.project_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NodeID(); ok {
		if err := mindmapnode.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "MindMapNode.node_id": %w`, err)}
		}
	}
	return nil
}

func (_u *MindMapNodeUpdateOne) sqlSave(ctx context.Context) (_node *MindMapNode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mindmapnode.Table, mindmapnode.Columns, sqlgraph.NewFieldSpec(mindmapnode.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MindMapNode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mindmapnode.FieldID)
		for _, f := range fields {
			if !mindmapnode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mindmapnode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(mindmapnode.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(mindmapnode.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(mindmapnode.FieldNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(mindmapnode.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(mindmapnode.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(mindmapnode.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(mindmapnode.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Files(); ok {
		_spec.SetField(mindmapnode.FieldFiles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFiles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mindmapnode.FieldFiles, value)
		})
	}
	if _u.mutation.FilesCleared() {
		_spec.ClearField(mindmapnode.FieldFiles, field.TypeJSON)
	}
	if value, ok := _u.mutation.TitleUpdatedAt(); ok {
		_spec.SetField(mindmapnode.FieldTitleUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TitleUpdatedAtCleared() {
		_spec.ClearField(mindmapnode.FieldTitleUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ContentUpdatedAt(); ok {
		_spec.SetField(mindmapnode.FieldContentUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ContentUpdatedAtCleared() {
		_spec.ClearField(mindmapnode.FieldContentUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FilesUpdatedAt(); ok {
		_spec.SetField(mindmapnode.FieldFilesUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FilesUpdatedAtCleared() {
		_spec.ClearField(mindmapnode.FieldFilesUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mindmapnode.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mindmapnode.FieldDeletedAt, field.TypeTime)
	}
	_node = &MindMapNode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mindmapnode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
