// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/notificationdelivery"
)

// NotificationDeliveryCreate is the builder for creating a NotificationDelivery entity.
type NotificationDeliveryCreate struct {
	config
	mutation *NotificationDeliveryMutation
	hooks    []Hook
}

// SetEventID sets the "event_id" field.
func (_c *NotificationDeliveryCreate) SetEventID(v string) *NotificationDeliveryCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *NotificationDeliveryCreate) SetSubscriptionID(v string) *NotificationDeliveryCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *NotificationDeliveryCreate) SetPayload(v []byte) *NotificationDeliveryCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *NotificationDeliveryCreate) SetStatus(v string) *NotificationDeliveryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *NotificationDeliveryCreate) SetAttempts(v int) *NotificationDeliveryCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *NotificationDeliveryCreate) SetNillableAttempts(v *int) *NotificationDeliveryCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_c *NotificationDeliveryCreate) SetNextAttemptAt(v time.Time) *NotificationDeliveryCreate {
	_c.mutation.SetNextAttemptAt(v)
	return _c
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_c *NotificationDeliveryCreate) SetNillableNextAttemptAt(v *time.Time) *NotificationDeliveryCreate {
	if v != nil {
		_c.SetNextAttemptAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *NotificationDeliveryCreate) SetLastError(v string) *NotificationDeliveryCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *NotificationDeliveryCreate) SetNillableLastError(v *string) *NotificationDeliveryCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationDeliveryCreate) SetCreatedAt(v time.Time) *NotificationDeliveryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationDeliveryCreate) SetNillableCreatedAt(v *time.Time) *NotificationDeliveryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationDeliveryCreate) SetUpdatedAt(v time.Time) *NotificationDeliveryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotificationDeliveryCreate) SetNillableUpdatedAt(v *time.Time) *NotificationDeliveryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NotificationDeliveryCreate) SetID(v string) *NotificationDeliveryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the NotificationDeliveryMutation object of the builder.
func (_c *NotificationDeliveryCreate) Mutation() *NotificationDeliveryMutation {
	return _c.mutation
}

// Save creates the NotificationDelivery in the database.
func (_c *NotificationDeliveryCreate) Save(ctx context.Context) (*NotificationDelivery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationDeliveryCreate) SaveX(ctx context.Context) *NotificationDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationDeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationDeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationDeliveryCreate) defaults() {
	if _, ok := _c.mutation.Attempts(); !ok {
		v := notificationdelivery.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.NextAttemptAt(); !ok {
		v := notificationdelivery.DefaultNextAttemptAt()
		_c.mutation.SetNextAttemptAt(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := notificationdelivery.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notificationdelivery.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := notificationdelivery.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationDeliveryCreate) check() error {
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "NotificationDelivery.event_id"`)}
	}
	if v, ok := _c.mutation.EventID(); ok {
		if err := notificationdelivery.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "NotificationDelivery.event_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "NotificationDelivery.subscription_id"`)}
	}
	if v, ok := _c.mutation.SubscriptionID(); ok {
		if err := notificationdelivery.SubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "subscription_id", err: fmt.Errorf(`ent: validator failed for field "NotificationDelivery.subscription_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "NotificationDelivery.payload"`)}
	}
	if v, ok := _c.mutation.Payload(); ok {
		if err := notificationdelivery.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "NotificationDelivery.payload": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "NotificationDelivery.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := notificationdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NotificationDelivery.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "NotificationDelivery.attempts"`)}
	}
	if _, ok := _c.mutation.NextAttemptAt(); !ok {
		return &ValidationError{Name: "next_attempt_at", err: errors.New(`ent: missing required field "NotificationDelivery.next_attempt_at"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "NotificationDelivery.last_error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotificationDelivery.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotificationDelivery.updated_at"`)}
	}
	return nil
}

func (_c *NotificationDeliveryCreate) sqlSave(ctx context.Context) (*NotificationDelivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected NotificationDelivery.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationDeliveryCreate) createSpec() (*NotificationDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationDelivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationdelivery.Table, sqlgraph.NewFieldSpec(notificationdelivery.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(notificationdelivery.FieldEventID, field.TypeString, value)
		_node.EventID = value
	}
	if value, ok := _c.mutation.SubscriptionID(); ok {
		_spec.SetField(notificationdelivery.FieldSubscriptionID, field.TypeString, value)
		_node.SubscriptionID = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(notificationdelivery.FieldPayload, field.TypeBytes, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(notificationdelivery.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(notificationdelivery.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.NextAttemptAt(); ok {
		_spec.SetField(notificationdelivery.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(notificationdelivery.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notificationdelivery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationdelivery.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// NotificationDeliveryCreateBulk is the builder for creating many NotificationDelivery entities in bulk.
type NotificationDeliveryCreateBulk struct {
	config
	err      error
	builders []*NotificationDeliveryCreate
}

// Save creates the NotificationDelivery entities in the database.
func (_c *NotificationDeliveryCreateBulk) Save(ctx context.Context) ([]*NotificationDelivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationDelivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationDeliveryCreateBulk) SaveX(ctx context.Context) []*NotificationDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
