// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/quickcommand"
)

// QuickCommandCreate is the builder for creating a QuickCommand entity.
type QuickCommandCreate struct {
	config
	mutation *QuickCommandMutation
	hooks    []Hook
}

// SetContent sets the "content" field.
func (_c *QuickCommandCreate) SetContent(v string) *QuickCommandCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuickCommandCreate) SetCreatedAt(v time.Time) *QuickCommandCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuickCommandCreate) SetNillableCreatedAt(v *time.Time) *QuickCommandCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuickCommandCreate) SetID(v string) *QuickCommandCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the QuickCommandMutation object of the builder.
func (_c *QuickCommandCreate) Mutation() *QuickCommandMutation {
	return _c.mutation
}

// Save creates the QuickCommand in the database.
func (_c *QuickCommandCreate) Save(ctx context.Context) (*QuickCommand, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuickCommandCreate) SaveX(ctx context.Context) *QuickCommand {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuickCommandCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuickCommandCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuickCommandCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quickcommand.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuickCommandCreate) check() error {
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "QuickCommand.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := quickcommand.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "QuickCommand.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QuickCommand.created_at"`)}
	}
	return nil
}

func (_c *QuickCommandCreate) sqlSave(ctx context.Context) (*QuickCommand, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected QuickCommand.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuickCommandCreate) createSpec() (*QuickCommand, *sqlgraph.CreateSpec) {
	var (
		_node = &QuickCommand{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quickcommand.Table, sqlgraph.NewFieldSpec(quickcommand.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(quickcommand.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quickcommand.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// QuickCommandCreateBulk is the builder for creating many QuickCommand entities in bulk.
type QuickCommandCreateBulk struct {
	config
	err      error
	builders []*QuickCommandCreate
}

// Save creates the QuickCommand entities in the database.
func (_c *QuickCommandCreateBulk) Save(ctx context.Context) ([]*QuickCommand, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*QuickCommand, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuickCommandMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuickCommandCreateBulk) SaveX(ctx context.Context) []*QuickCommand {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuickCommandCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuickCommandCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
