// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nzlov/anycode/internal/domain/session"
	entsession "github.com/nzlov/anycode/internal/infra/entstore/ent/session"
)

// SessionCreate is the builder for creating a Session entity.
type SessionCreate struct {
	config
	mutation *SessionMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *SessionCreate) SetProjectID(v string) *SessionCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetRequirement sets the "requirement" field.
func (_c *SessionCreate) SetRequirement(v string) *SessionCreate {
	_c.mutation.SetRequirement(v)
	return _c
}

// SetNillableRequirement sets the "requirement" field if the given value is not nil.
func (_c *SessionCreate) SetNillableRequirement(v *string) *SessionCreate {
	if v != nil {
		_c.SetRequirement(*v)
	}
	return _c
}

// SetMode sets the "mode" field.
func (_c *SessionCreate) SetMode(v string) *SessionCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SessionCreate) SetStatus(v string) *SessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *SessionCreate) SetPriority(v string) *SessionCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *SessionCreate) SetNillablePriority(v *string) *SessionCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetCloseReason sets the "close_reason" field.
func (_c *SessionCreate) SetCloseReason(v string) *SessionCreate {
	_c.mutation.SetCloseReason(v)
	return _c
}

// SetNillableCloseReason sets the "close_reason" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCloseReason(v *string) *SessionCreate {
	if v != nil {
		_c.SetCloseReason(*v)
	}
	return _c
}

// SetBaseBranch sets the "base_branch" field.
func (_c *SessionCreate) SetBaseBranch(v string) *SessionCreate {
	_c.mutation.SetBaseBranch(v)
	return _c
}

// SetNillableBaseBranch sets the "base_branch" field if the given value is not nil.
func (_c *SessionCreate) SetNillableBaseBranch(v *string) *SessionCreate {
	if v != nil {
		_c.SetBaseBranch(*v)
	}
	return _c
}

// SetWorktreePath sets the "worktree_path" field.
func (_c *SessionCreate) SetWorktreePath(v string) *SessionCreate {
	_c.mutation.SetWorktreePath(v)
	return _c
}

// SetNillableWorktreePath sets the "worktree_path" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreePath(v *string) *SessionCreate {
	if v != nil {
		_c.SetWorktreePath(*v)
	}
	return _c
}

// SetWorktreeBranch sets the "worktree_branch" field.
func (_c *SessionCreate) SetWorktreeBranch(v string) *SessionCreate {
	_c.mutation.SetWorktreeBranch(v)
	return _c
}

// SetNillableWorktreeBranch sets the "worktree_branch" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeBranch(v *string) *SessionCreate {
	if v != nil {
		_c.SetWorktreeBranch(*v)
	}
	return _c
}

// SetWorktreeBaseCommit sets the "worktree_base_commit" field.
func (_c *SessionCreate) SetWorktreeBaseCommit(v string) *SessionCreate {
	_c.mutation.SetWorktreeBaseCommit(v)
	return _c
}

// SetNillableWorktreeBaseCommit sets the "worktree_base_commit" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeBaseCommit(v *string) *SessionCreate {
	if v != nil {
		_c.SetWorktreeBaseCommit(*v)
	}
	return _c
}

// SetWorktreeCleanupStatus sets the "worktree_cleanup_status" field.
func (_c *SessionCreate) SetWorktreeCleanupStatus(v string) *SessionCreate {
	_c.mutation.SetWorktreeCleanupStatus(v)
	return _c
}

// SetNillableWorktreeCleanupStatus sets the "worktree_cleanup_status" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeCleanupStatus(v *string) *SessionCreate {
	if v != nil {
		_c.SetWorktreeCleanupStatus(*v)
	}
	return _c
}

// SetWorktreeCleanupAttempts sets the "worktree_cleanup_attempts" field.
func (_c *SessionCreate) SetWorktreeCleanupAttempts(v int) *SessionCreate {
	_c.mutation.SetWorktreeCleanupAttempts(v)
	return _c
}

// SetNillableWorktreeCleanupAttempts sets the "worktree_cleanup_attempts" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeCleanupAttempts(v *int) *SessionCreate {
	if v != nil {
		_c.SetWorktreeCleanupAttempts(*v)
	}
	return _c
}

// SetWorktreeOwnershipToken sets the "worktree_ownership_token" field.
func (_c *SessionCreate) SetWorktreeOwnershipToken(v string) *SessionCreate {
	_c.mutation.SetWorktreeOwnershipToken(v)
	return _c
}

// SetNillableWorktreeOwnershipToken sets the "worktree_ownership_token" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeOwnershipToken(v *string) *SessionCreate {
	if v != nil {
		_c.SetWorktreeOwnershipToken(*v)
	}
	return _c
}

// SetWorktreeOwnershipConfirmedAt sets the "worktree_ownership_confirmed_at" field.
func (_c *SessionCreate) SetWorktreeOwnershipConfirmedAt(v time.Time) *SessionCreate {
	_c.mutation.SetWorktreeOwnershipConfirmedAt(v)
	return _c
}

// SetNillableWorktreeOwnershipConfirmedAt sets the "worktree_ownership_confirmed_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeOwnershipConfirmedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetWorktreeOwnershipConfirmedAt(*v)
	}
	return _c
}

// SetWorktreeCleanupRequestedAt sets the "worktree_cleanup_requested_at" field.
func (_c *SessionCreate) SetWorktreeCleanupRequestedAt(v time.Time) *SessionCreate {
	_c.mutation.SetWorktreeCleanupRequestedAt(v)
	return _c
}

// SetNillableWorktreeCleanupRequestedAt sets the "worktree_cleanup_requested_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeCleanupRequestedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetWorktreeCleanupRequestedAt(*v)
	}
	return _c
}

// SetWorktreeCleanupLastAt sets the "worktree_cleanup_last_at" field.
func (_c *SessionCreate) SetWorktreeCleanupLastAt(v time.Time) *SessionCreate {
	_c.mutation.SetWorktreeCleanupLastAt(v)
	return _c
}

// SetNillableWorktreeCleanupLastAt sets the "worktree_cleanup_last_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeCleanupLastAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetWorktreeCleanupLastAt(*v)
	}
	return _c
}

// SetWorktreeCleanupNextAt sets the "worktree_cleanup_next_at" field.
func (_c *SessionCreate) SetWorktreeCleanupNextAt(v time.Time) *SessionCreate {
	_c.mutation.SetWorktreeCleanupNextAt(v)
	return _c
}

// SetNillableWorktreeCleanupNextAt sets the "worktree_cleanup_next_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeCleanupNextAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetWorktreeCleanupNextAt(*v)
	}
	return _c
}

// SetWorktreeCleanupCompletedAt sets the "worktree_cleanup_completed_at" field.
func (_c *SessionCreate) SetWorktreeCleanupCompletedAt(v time.Time) *SessionCreate {
	_c.mutation.SetWorktreeCleanupCompletedAt(v)
	return _c
}

// SetNillableWorktreeCleanupCompletedAt sets the "worktree_cleanup_completed_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeCleanupCompletedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetWorktreeCleanupCompletedAt(*v)
	}
	return _c
}

// SetWorktreeCleanupErrorCode sets the "worktree_cleanup_error_code" field.
func (_c *SessionCreate) SetWorktreeCleanupErrorCode(v string) *SessionCreate {
	_c.mutation.SetWorktreeCleanupErrorCode(v)
	return _c
}

// SetNillableWorktreeCleanupErrorCode sets the "worktree_cleanup_error_code" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeCleanupErrorCode(v *string) *SessionCreate {
	if v != nil {
		_c.SetWorktreeCleanupErrorCode(*v)
	}
	return _c
}

// SetWorktreeCleanupError sets the "worktree_cleanup_error" field.
func (_c *SessionCreate) SetWorktreeCleanupError(v string) *SessionCreate {
	_c.mutation.SetWorktreeCleanupError(v)
	return _c
}

// SetNillableWorktreeCleanupError sets the "worktree_cleanup_error" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeCleanupError(v *string) *SessionCreate {
	if v != nil {
		_c.SetWorktreeCleanupError(*v)
	}
	return _c
}

// SetWorktreeCleanupRetryable sets the "worktree_cleanup_retryable" field.
func (_c *SessionCreate) SetWorktreeCleanupRetryable(v bool) *SessionCreate {
	_c.mutation.SetWorktreeCleanupRetryable(v)
	return _c
}

// SetNillableWorktreeCleanupRetryable sets the "worktree_cleanup_retryable" field if the given value is not nil.
func (_c *SessionCreate) SetNillableWorktreeCleanupRetryable(v *bool) *SessionCreate {
	if v != nil {
		_c.SetWorktreeCleanupRetryable(*v)
	}
	return _c
}

// SetCodexSessionID sets the "codex_session_id" field.
func (_c *SessionCreate) SetCodexSessionID(v string) *SessionCreate {
	_c.mutation.SetCodexSessionID(v)
	return _c
}

// SetNillableCodexSessionID sets the "codex_session_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCodexSessionID(v *string) *SessionCreate {
	if v != nil {
		_c.SetCodexSessionID(*v)
	}
	return _c
}

// SetCodexModel sets the "codex_model" field.
func (_c *SessionCreate) SetCodexModel(v string) *SessionCreate {
	_c.mutation.SetCodexModel(v)
	return _c
}

// SetNillableCodexModel sets the "codex_model" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCodexModel(v *string) *SessionCreate {
	if v != nil {
		_c.SetCodexModel(*v)
	}
	return _c
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_c *SessionCreate) SetReasoningEffort(v string) *SessionCreate {
	_c.mutation.SetReasoningEffort(v)
	return _c
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_c *SessionCreate) SetNillableReasoningEffort(v *string) *SessionCreate {
	if v != nil {
		_c.SetReasoningEffort(*v)
	}
	return _c
}

// SetPermissionMode sets the "permission_mode" field.
func (_c *SessionCreate) SetPermissionMode(v string) *SessionCreate {
	_c.mutation.SetPermissionMode(v)
	return _c
}

// SetNillablePermissionMode sets the "permission_mode" field if the given value is not nil.
func (_c *SessionCreate) SetNillablePermissionMode(v *string) *SessionCreate {
	if v != nil {
		_c.SetPermissionMode(*v)
	}
	return _c
}

// SetFastMode sets the "fast_mode" field.
func (_c *SessionCreate) SetFastMode(v bool) *SessionCreate {
	_c.mutation.SetFastMode(v)
	return _c
}

// SetNillableFastMode sets the "fast_mode" field if the given value is not nil.
func (_c *SessionCreate) SetNillableFastMode(v *bool) *SessionCreate {
	if v != nil {
		_c.SetFastMode(*v)
	}
	return _c
}

// SetTodoList sets the "todo_list" field.
func (_c *SessionCreate) SetTodoList(v session.TodoList) *SessionCreate {
	_c.mutation.SetTodoList(v)
	return _c
}

// SetNillableTodoList sets the "todo_list" field if the given value is not nil.
func (_c *SessionCreate) SetNillableTodoList(v *session.TodoList) *SessionCreate {
	if v != nil {
		_c.SetTodoList(*v)
	}
	return _c
}

// SetArtifactCount sets the "artifact_count" field.
func (_c *SessionCreate) SetArtifactCount(v int) *SessionCreate {
	_c.mutation.SetArtifactCount(v)
	return _c
}

// SetNillableArtifactCount sets the "artifact_count" field if the given value is not nil.
func (_c *SessionCreate) SetNillableArtifactCount(v *int) *SessionCreate {
	if v != nil {
		_c.SetArtifactCount(*v)
	}
	return _c
}

// SetFilesChanged sets the "files_changed" field.
func (_c *SessionCreate) SetFilesChanged(v int) *SessionCreate {
	_c.mutation.SetFilesChanged(v)
	return _c
}

// SetNillableFilesChanged sets the "files_changed" field if the given value is not nil.
func (_c *SessionCreate) SetNillableFilesChanged(v *int) *SessionCreate {
	if v != nil {
		_c.SetFilesChanged(*v)
	}
	return _c
}

// SetQueuedAt sets the "queued_at" field.
func (_c *SessionCreate) SetQueuedAt(v time.Time) *SessionCreate {
	_c.mutation.SetQueuedAt(v)
	return _c
}

// SetNillableQueuedAt sets the "queued_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableQueuedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetQueuedAt(*v)
	}
	return _c
}

// SetQueueKind sets the "queue_kind" field.
func (_c *SessionCreate) SetQueueKind(v string) *SessionCreate {
	_c.mutation.SetQueueKind(v)
	return _c
}

// SetNillableQueueKind sets the "queue_kind" field if the given value is not nil.
func (_c *SessionCreate) SetNillableQueueKind(v *string) *SessionCreate {
	if v != nil {
		_c.SetQueueKind(*v)
	}
	return _c
}

// SetQueuePriority sets the "queue_priority" field.
func (_c *SessionCreate) SetQueuePriority(v string) *SessionCreate {
	_c.mutation.SetQueuePriority(v)
	return _c
}

// SetNillableQueuePriority sets the "queue_priority" field if the given value is not nil.
func (_c *SessionCreate) SetNillableQueuePriority(v *string) *SessionCreate {
	if v != nil {
		_c.SetQueuePriority(*v)
	}
	return _c
}

// SetQueueInitialStart sets the "queue_initial_start" field.
func (_c *SessionCreate) SetQueueInitialStart(v bool) *SessionCreate {
	_c.mutation.SetQueueInitialStart(v)
	return _c
}

// SetNillableQueueInitialStart sets the "queue_initial_start" field if the given value is not nil.
func (_c *SessionCreate) SetNillableQueueInitialStart(v *bool) *SessionCreate {
	if v != nil {
		_c.SetQueueInitialStart(*v)
	}
	return _c
}

// SetQueueReviewAfterReuseFailure sets the "queue_review_after_reuse_failure" field.
func (_c *SessionCreate) SetQueueReviewAfterReuseFailure(v bool) *SessionCreate {
	_c.mutation.SetQueueReviewAfterReuseFailure(v)
	return _c
}

// SetNillableQueueReviewAfterReuseFailure sets the "queue_review_after_reuse_failure" field if the given value is not nil.
func (_c *SessionCreate) SetNillableQueueReviewAfterReuseFailure(v *bool) *SessionCreate {
	if v != nil {
		_c.SetQueueReviewAfterReuseFailure(*v)
	}
	return _c
}

// SetQueueWorkflowRunID sets the "queue_workflow_run_id" field.
func (_c *SessionCreate) SetQueueWorkflowRunID(v string) *SessionCreate {
	_c.mutation.SetQueueWorkflowRunID(v)
	return _c
}

// SetNillableQueueWorkflowRunID sets the "queue_workflow_run_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableQueueWorkflowRunID(v *string) *SessionCreate {
	if v != nil {
		_c.SetQueueWorkflowRunID(*v)
	}
	return _c
}

// SetQueueNodeRunID sets the "queue_node_run_id" field.
func (_c *SessionCreate) SetQueueNodeRunID(v string) *SessionCreate {
	_c.mutation.SetQueueNodeRunID(v)
	return _c
}

// SetNillableQueueNodeRunID sets the "queue_node_run_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableQueueNodeRunID(v *string) *SessionCreate {
	if v != nil {
		_c.SetQueueNodeRunID(*v)
	}
	return _c
}

// SetQueuePrompt sets the "queue_prompt" field.
func (_c *SessionCreate) SetQueuePrompt(v string) *SessionCreate {
	_c.mutation.SetQueuePrompt(v)
	return _c
}

// SetNillableQueuePrompt sets the "queue_prompt" field if the given value is not nil.
func (_c *SessionCreate) SetNillableQueuePrompt(v *string) *SessionCreate {
	if v != nil {
		_c.SetQueuePrompt(*v)
	}
	return _c
}

// SetQueueResumeCodexSessionID sets the "queue_resume_codex_session_id" field.
func (_c *SessionCreate) SetQueueResumeCodexSessionID(v string) *SessionCreate {
	_c.mutation.SetQueueResumeCodexSessionID(v)
	return _c
}

// SetNillableQueueResumeCodexSessionID sets the "queue_resume_codex_session_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableQueueResumeCodexSessionID(v *string) *SessionCreate {
	if v != nil {
		_c.SetQueueResumeCodexSessionID(*v)
	}
	return _c
}

// SetQueueResumeOfProcessRunID sets the "queue_resume_of_process_run_id" field.
func (_c *SessionCreate) SetQueueResumeOfProcessRunID(v string) *SessionCreate {
	_c.mutation.SetQueueResumeOfProcessRunID(v)
	return _c
}

// SetNillableQueueResumeOfProcessRunID sets the "queue_resume_of_process_run_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableQueueResumeOfProcessRunID(v *string) *SessionCreate {
	if v != nil {
		_c.SetQueueResumeOfProcessRunID(*v)
	}
	return _c
}

// SetQueueAnswerBatchID sets the "queue_answer_batch_id" field.
func (_c *SessionCreate) SetQueueAnswerBatchID(v string) *SessionCreate {
	_c.mutation.SetQueueAnswerBatchID(v)
	return _c
}

// SetNillableQueueAnswerBatchID sets the "queue_answer_batch_id" field if the given value is not nil.
func (_c *SessionCreate) SetNillableQueueAnswerBatchID(v *string) *SessionCreate {
	if v != nil {
		_c.SetQueueAnswerBatchID(*v)
	}
	return _c
}

// SetAppliedSystemCommands sets the "applied_system_commands" field.
func (_c *SessionCreate) SetAppliedSystemCommands(v map[string]bool) *SessionCreate {
	_c.mutation.SetAppliedSystemCommands(v)
	return _c
}

// SetLastRunAt sets the "last_run_at" field.
func (_c *SessionCreate) SetLastRunAt(v time.Time) *SessionCreate {
	_c.mutation.SetLastRunAt(v)
	return _c
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableLastRunAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetLastRunAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SessionCreate) SetCreatedAt(v time.Time) *SessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCreatedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SessionCreate) SetUpdatedAt(v time.Time) *SessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableUpdatedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetClosedAt sets the "closed_at" field.
func (_c *SessionCreate) SetClosedAt(v time.Time) *SessionCreate {
	_c.mutation.SetClosedAt(v)
	return _c
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableClosedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetClosedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SessionCreate) SetID(v string) *SessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SessionMutation object of the builder.
func (_c *SessionCreate) Mutation() *SessionMutation {
	return _c.mutation
}

// Save creates the Session in the database.
func (_c *SessionCreate) Save(ctx context.Context) (*Session, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionCreate) SaveX(ctx context.Context) *Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SessionCreate) defaults() {
	if _, ok := _c.mutation.Requirement(); !ok {
		v := entsession.DefaultRequirement
		_c.mutation.SetRequirement(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := entsession.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.BaseBranch(); !ok {
		v := entsession.DefaultBaseBranch
		_c.mutation.SetBaseBranch(v)
	}
	if _, ok := _c.mutation.WorktreePath(); !ok {
		v := entsession.DefaultWorktreePath
		_c.mutation.SetWorktreePath(v)
	}
	if _, ok := _c.mutation.WorktreeBranch(); !ok {
		v := entsession.DefaultWorktreeBranch
		_c.mutation.SetWorktreeBranch(v)
	}
	if _, ok := _c.mutation.WorktreeBaseCommit(); !ok {
		v := entsession.DefaultWorktreeBaseCommit
		_c.mutation.SetWorktreeBaseCommit(v)
	}
	if _, ok := _c.mutation.WorktreeCleanupStatus(); !ok {
		v := entsession.DefaultWorktreeCleanupStatus
		_c.mutation.SetWorktreeCleanupStatus(v)
	}
	if _, ok := _c.mutation.WorktreeCleanupAttempts(); !ok {
		v := entsession.DefaultWorktreeCleanupAttempts
		_c.mutation.SetWorktreeCleanupAttempts(v)
	}
	if _, ok := _c.mutation.WorktreeOwnershipToken(); !ok {
		v := entsession.DefaultWorktreeOwnershipToken
		_c.mutation.SetWorktreeOwnershipToken(v)
	}
	if _, ok := _c.mutation.WorktreeCleanupErrorCode(); !ok {
		v := entsession.DefaultWorktreeCleanupErrorCode
		_c.mutation.SetWorktreeCleanupErrorCode(v)
	}
	if _, ok := _c.mutation.WorktreeCleanupError(); !ok {
		v := entsession.DefaultWorktreeCleanupError
		_c.mutation.SetWorktreeCleanupError(v)
	}
	if _, ok := _c.mutation.WorktreeCleanupRetryable(); !ok {
		v := entsession.DefaultWorktreeCleanupRetryable
		_c.mutation.SetWorktreeCleanupRetryable(v)
	}
	if _, ok := _c.mutation.CodexSessionID(); !ok {
		v := entsession.DefaultCodexSessionID
		_c.mutation.SetCodexSessionID(v)
	}
	if _, ok := _c.mutation.CodexModel(); !ok {
		v := entsession.DefaultCodexModel
		_c.mutation.SetCodexModel(v)
	}
	if _, ok := _c.mutation.ReasoningEffort(); !ok {
		v := entsession.DefaultReasoningEffort
		_c.mutation.SetReasoningEffort(v)
	}
	if _, ok := _c.mutation.PermissionMode(); !ok {
		v := entsession.DefaultPermissionMode
		_c.mutation.SetPermissionMode(v)
	}
	if _, ok := _c.mutation.FastMode(); !ok {
		v := entsession.DefaultFastMode
		_c.mutation.SetFastMode(v)
	}
	if _, ok := _c.mutation.ArtifactCount(); !ok {
		v := entsession.DefaultArtifactCount
		_c.mutation.SetArtifactCount(v)
	}
	if _, ok := _c.mutation.FilesChanged(); !ok {
		v := entsession.DefaultFilesChanged
		_c.mutation.SetFilesChanged(v)
	}
	if _, ok := _c.mutation.QueueKind(); !ok {
		v := entsession.DefaultQueueKind
		_c.mutation.SetQueueKind(v)
	}
	if _, ok := _c.mutation.QueuePriority(); !ok {
		v := entsession.DefaultQueuePriority
		_c.mutation.SetQueuePriority(v)
	}
	if _, ok := _c.mutation.QueueReviewAfterReuseFailure(); !ok {
		v := entsession.DefaultQueueReviewAfterReuseFailure
		_c.mutation.SetQueueReviewAfterReuseFailure(v)
	}
	if _, ok := _c.mutation.QueueWorkflowRunID(); !ok {
		v := entsession.DefaultQueueWorkflowRunID
		_c.mutation.SetQueueWorkflowRunID(v)
	}
	if _, ok := _c.mutation.QueueNodeRunID(); !ok {
		v := entsession.DefaultQueueNodeRunID
		_c.mutation.SetQueueNodeRunID(v)
	}
	if _, ok := _c.mutation.QueuePrompt(); !ok {
		v := entsession.DefaultQueuePrompt
		_c.mutation.SetQueuePrompt(v)
	}
	if _, ok := _c.mutation.QueueResumeCodexSessionID(); !ok {
		v := entsession.DefaultQueueResumeCodexSessionID
		_c.mutation.SetQueueResumeCodexSessionID(v)
	}
	if _, ok := _c.mutation.QueueResumeOfProcessRunID(); !ok {
		v := entsession.DefaultQueueResumeOfProcessRunID
		_c.mutation.SetQueueResumeOfProcessRunID(v)
	}
	if _, ok := _c.mutation.QueueAnswerBatchID(); !ok {
		v := entsession.DefaultQueueAnswerBatchID
		_c.mutation.SetQueueAnswerBatchID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := entsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := entsession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Session.project_id"`)}
	}
	if v, ok := _c.mutation.ProjectID(); ok {
		if err := entsession.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "Session.project_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Requirement(); !ok {
		return &ValidationError{Name: "requirement", err: errors.New(`ent: missing required field "Session.requirement"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Session.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := entsession.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Session.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Session.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := entsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Session.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Session.priority"`)}
	}
	if _, ok := _c.mutation.BaseBranch(); !ok {
		return &ValidationError{Name: "base_branch", err: errors.New(`ent: missing required field "Session.base_branch"`)}
	}
	if _, ok := _c.mutation.WorktreePath(); !ok {
		return &ValidationError{Name: "worktree_path", err: errors.New(`ent: missing required field "Session.worktree_path"`)}
	}
	if _, ok := _c.mutation.WorktreeBranch(); !ok {
		return &ValidationError{Name: "worktree_branch", err: errors.New(`ent: missing required field "Session.worktree_branch"`)}
	}
	if _, ok := _c.mutation.WorktreeBaseCommit(); !ok {
		return &ValidationError{Name: "worktree_base_commit", err: errors.New(`ent: missing required field "Session.worktree_base_commit"`)}
	}
	if _, ok := _c.mutation.WorktreeCleanupStatus(); !ok {
		return &ValidationError{Name: "worktree_cleanup_status", err: errors.New(`ent: missing required field "Session.worktree_cleanup_status"`)}
	}
	if _, ok := _c.mutation.WorktreeCleanupAttempts(); !ok {
		return &ValidationError{Name: "worktree_cleanup_attempts", err: errors.New(`ent: missing required field "Session.worktree_cleanup_attempts"`)}
	}
	if _, ok := _c.mutation.WorktreeOwnershipToken(); !ok {
		return &ValidationError{Name: "worktree_ownership_token", err: errors.New(`ent: missing required field "Session.worktree_ownership_token"`)}
	}
	if _, ok := _c.mutation.WorktreeCleanupErrorCode(); !ok {
		return &ValidationError{Name: "worktree_cleanup_error_code", err: errors.New(`ent: missing required field "Session.worktree_cleanup_error_code"`)}
	}
	if _, ok := _c.mutation.WorktreeCleanupError(); !ok {
		return &ValidationError{Name: "worktree_cleanup_error", err: errors.New(`ent: missing required field "Session.worktree_cleanup_error"`)}
	}
	if _, ok := _c.mutation.WorktreeCleanupRetryable(); !ok {
		return &ValidationError{Name: "worktree_cleanup_retryable", err: errors.New(`ent: missing required field "Session.worktree_cleanup_retryable"`)}
	}
	if _, ok := _c.mutation.CodexSessionID(); !ok {
		return &ValidationError{Name: "codex_session_id", err: errors.New(`ent: missing required field "Session.codex_session_id"`)}
	}
	if _, ok := _c.mutation.CodexModel(); !ok {
		return &ValidationError{Name: "codex_model", err: errors.New(`ent: missing required field "Session.codex_model"`)}
	}
	if _, ok := _c.mutation.ReasoningEffort(); !ok {
		return &ValidationError{Name: "reasoning_effort", err: errors.New(`ent: missing required field "Session.reasoning_effort"`)}
	}
	if _, ok := _c.mutation.PermissionMode(); !ok {
		return &ValidationError{Name: "permission_mode", err: errors.New(`ent: missing required field "Session.permission_mode"`)}
	}
	if _, ok := _c.mutation.FastMode(); !ok {
		return &ValidationError{Name: "fast_mode", err: errors.New(`ent: missing required field "Session.fast_mode"`)}
	}
	if _, ok := _c.mutation.ArtifactCount(); !ok {
		return &ValidationError{Name: "artifact_count", err: errors.New(`ent: missing required field "Session.artifact_count"`)}
	}
	if v, ok := _c.mutation.ArtifactCount(); ok {
		if err := entsession.ArtifactCountValidator(v); err != nil {
			return &ValidationError{Name: "artifact_count", err: fmt.Errorf(`ent: validator failed for field "Session.artifact_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FilesChanged(); !ok {
		return &ValidationError{Name: "files_changed", err: errors.New(`ent: missing required field "Session.files_changed"`)}
	}
	if v, ok := _c.mutation.FilesChanged(); ok {
		if err := entsession.FilesChangedValidator(v); err != nil {
			return &ValidationError{Name: "files_changed", err: fmt.Errorf(`ent: validator failed for field "Session.files_changed": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QueueKind(); !ok {
		return &ValidationError{Name: "queue_kind", err: errors.New(`ent: missing required field "Session.queue_kind"`)}
	}
	if _, ok := _c.mutation.QueuePriority(); !ok {
		return &ValidationError{Name: "queue_priority", err: errors.New(`ent: missing required field "Session.queue_priority"`)}
	}
	if _, ok := _c.mutation.QueueReviewAfterReuseFailure(); !ok {
		return &ValidationError{Name: "queue_review_after_reuse_failure", err: errors.New(`ent: missing required field "Session.queue_review_after_reuse_failure"`)}
	}
	if _, ok := _c.mutation.QueueWorkflowRunID(); !ok {
		return &ValidationError{Name: "queue_workflow_run_id", err: errors.New(`ent: missing required field "Session.queue_workflow_run_id"`)}
	}
	if _, ok := _c.mutation.QueueNodeRunID(); !ok {
		return &ValidationError{Name: "queue_node_run_id", err: errors.New(`ent: missing required field "Session.queue_node_run_id"`)}
	}
	if _, ok := _c.mutation.QueuePrompt(); !ok {
		return &ValidationError{Name: "queue_prompt", err: errors.New(`ent: missing required field "Session.queue_prompt"`)}
	}
	if _, ok := _c.mutation.QueueResumeCodexSessionID(); !ok {
		return &ValidationError{Name: "queue_resume_codex_session_id", err: errors.New(`ent: missing required field "Session.queue_resume_codex_session_id"`)}
	}
	if _, ok := _c.mutation.QueueResumeOfProcessRunID(); !ok {
		return &ValidationError{Name: "queue_resume_of_process_run_id", err: errors.New(`ent: missing required field "Session.queue_resume_of_process_run_id"`)}
	}
	if _, ok := _c.mutation.QueueAnswerBatchID(); !ok {
		return &ValidationError{Name: "queue_answer_batch_id", err: errors.New(`ent: missing required field "Session.queue_answer_batch_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Session.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Session.updated_at"`)}
	}
	return nil
}

func (_c *SessionCreate) sqlSave(ctx context.Context) (*Session, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Session.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionCreate) createSpec() (*Session, *sqlgraph.CreateSpec) {
	var (
		_node = &Session{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entsession.Table, sqlgraph.NewFieldSpec(entsession.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(entsession.FieldProjectID, field.TypeString, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.Requirement(); ok {
		_spec.SetField(entsession.FieldRequirement, field.TypeString, value)
		_node.Requirement = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(entsession.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(entsession.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(entsession.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.CloseReason(); ok {
		_spec.SetField(entsession.FieldCloseReason, field.TypeString, value)
		_node.CloseReason = &value
	}
	if value, ok := _c.mutation.BaseBranch(); ok {
		_spec.SetField(entsession.FieldBaseBranch, field.TypeString, value)
		_node.BaseBranch = value
	}
	if value, ok := _c.mutation.WorktreePath(); ok {
		_spec.SetField(entsession.FieldWorktreePath, field.TypeString, value)
		_node.WorktreePath = value
	}
	if value, ok := _c.mutation.WorktreeBranch(); ok {
		_spec.SetField(entsession.FieldWorktreeBranch, field.TypeString, value)
		_node.WorktreeBranch = value
	}
	if value, ok := _c.mutation.WorktreeBaseCommit(); ok {
		_spec.SetField(entsession.FieldWorktreeBaseCommit, field.TypeString, value)
		_node.WorktreeBaseCommit = value
	}
	if value, ok := _c.mutation.WorktreeCleanupStatus(); ok {
		_spec.SetField(entsession.FieldWorktreeCleanupStatus, field.TypeString, value)
		_node.WorktreeCleanupStatus = value
	}
	if value, ok := _c.mutation.WorktreeCleanupAttempts(); ok {
		_spec.SetField(entsession.FieldWorktreeCleanupAttempts, field.TypeInt, value)
		_node.WorktreeCleanupAttempts = value
	}
	if value, ok := _c.mutation.WorktreeOwnershipToken(); ok {
		_spec.SetField(entsession.FieldWorktreeOwnershipToken, field.TypeString, value)
		_node.WorktreeOwnershipToken = value
	}
	if value, ok := _c.mutation.WorktreeOwnershipConfirmedAt(); ok {
		_spec.SetField(entsession.FieldWorktreeOwnershipConfirmedAt, field.TypeTime, value)
		_node.WorktreeOwnershipConfirmedAt = &value
	}
	if value, ok := _c.mutation.WorktreeCleanupRequestedAt(); ok {
		_spec.SetField(entsession.FieldWorktreeCleanupRequestedAt, field.TypeTime, value)
		_node.WorktreeCleanupRequestedAt = &value
	}
	if value, ok := _c.mutation.WorktreeCleanupLastAt(); ok {
		_spec.SetField(entsession.FieldWorktreeCleanupLastAt, field.TypeTime, value)
		_node.WorktreeCleanupLastAt = &value
	}
	if value, ok := _c.mutation.WorktreeCleanupNextAt(); ok {
		_spec.SetField(entsession.FieldWorktreeCleanupNextAt, field.TypeTime, value)
		_node.WorktreeCleanupNextAt = &value
	}
	if value, ok := _c.mutation.WorktreeCleanupCompletedAt(); ok {
		_spec.SetField(entsession.FieldWorktreeCleanupCompletedAt, field.TypeTime, value)
		_node.WorktreeCleanupCompletedAt = &value
	}
	if value, ok := _c.mutation.WorktreeCleanupErrorCode(); ok {
		_spec.SetField(entsession.FieldWorktreeCleanupErrorCode, field.TypeString, value)
		_node.WorktreeCleanupErrorCode = value
	}
	if value, ok := _c.mutation.WorktreeCleanupError(); ok {
		_spec.SetField(entsession.FieldWorktreeCleanupError, field.TypeString, value)
		_node.WorktreeCleanupError = value
	}
	if value, ok := _c.mutation.WorktreeCleanupRetryable(); ok {
		_spec.SetField(entsession.FieldWorktreeCleanupRetryable, field.TypeBool, value)
		_node.WorktreeCleanupRetryable = value
	}
	if value, ok := _c.mutation.CodexSessionID(); ok {
		_spec.SetField(entsession.FieldCodexSessionID, field.TypeString, value)
		_node.CodexSessionID = value
	}
	if value, ok := _c.mutation.CodexModel(); ok {
		_spec.SetField(entsession.FieldCodexModel, field.TypeString, value)
		_node.CodexModel = value
	}
	if value, ok := _c.mutation.ReasoningEffort(); ok {
		_spec.SetField(entsession.FieldReasoningEffort, field.TypeString, value)
		_node.ReasoningEffort = value
	}
	if value, ok := _c.mutation.PermissionMode(); ok {
		_spec.SetField(entsession.FieldPermissionMode, field.TypeString, value)
		_node.PermissionMode = value
	}
	if value, ok := _c.mutation.FastMode(); ok {
		_spec.SetField(entsession.FieldFastMode, field.TypeBool, value)
		_node.FastMode = value
	}
	if value, ok := _c.mutation.TodoList(); ok {
		_spec.SetField(entsession.FieldTodoList, field.TypeJSON, value)
		_node.TodoList = value
	}
	if value, ok := _c.mutation.ArtifactCount(); ok {
		_spec.SetField(entsession.FieldArtifactCount, field.TypeInt, value)
		_node.ArtifactCount = value
	}
	if value, ok := _c.mutation.FilesChanged(); ok {
		_spec.SetField(entsession.FieldFilesChanged, field.TypeInt, value)
		_node.FilesChanged = value
	}
	if value, ok := _c.mutation.QueuedAt(); ok {
		_spec.SetField(entsession.FieldQueuedAt, field.TypeTime, value)
		_node.QueuedAt = &value
	}
	if value, ok := _c.mutation.QueueKind(); ok {
		_spec.SetField(entsession.FieldQueueKind, field.TypeString, value)
		_node.QueueKind = value
	}
	if value, ok := _c.mutation.QueuePriority(); ok {
		_spec.SetField(entsession.FieldQueuePriority, field.TypeString, value)
		_node.QueuePriority = value
	}
	if value, ok := _c.mutation.QueueInitialStart(); ok {
		_spec.SetField(entsession.FieldQueueInitialStart, field.TypeBool, value)
		_node.QueueInitialStart = &value
	}
	if value, ok := _c.mutation.QueueReviewAfterReuseFailure(); ok {
		_spec.SetField(entsession.FieldQueueReviewAfterReuseFailure, field.TypeBool, value)
		_node.QueueReviewAfterReuseFailure = value
	}
	if value, ok := _c.mutation.QueueWorkflowRunID(); ok {
		_spec.SetField(entsession.FieldQueueWorkflowRunID, field.TypeString, value)
		_node.QueueWorkflowRunID = value
	}
	if value, ok := _c.mutation.QueueNodeRunID(); ok {
		_spec.SetField(entsession.FieldQueueNodeRunID, field.TypeString, value)
		_node.QueueNodeRunID = value
	}
	if value, ok := _c.mutation.QueuePrompt(); ok {
		_spec.SetField(entsession.FieldQueuePrompt, field.TypeString, value)
		_node.QueuePrompt = value
	}
	if value, ok := _c.mutation.QueueResumeCodexSessionID(); ok {
		_spec.SetField(entsession.FieldQueueResumeCodexSessionID, field.TypeString, value)
		_node.QueueResumeCodexSessionID = value
	}
	if value, ok := _c.mutation.QueueResumeOfProcessRunID(); ok {
		_spec.SetField(entsession.FieldQueueResumeOfProcessRunID, field.TypeString, value)
		_node.QueueResumeOfProcessRunID = value
	}
	if value, ok := _c.mutation.QueueAnswerBatchID(); ok {
		_spec.SetField(entsession.FieldQueueAnswerBatchID, field.TypeString, value)
		_node.QueueAnswerBatchID = value
	}
	if value, ok := _c.mutation.AppliedSystemCommands(); ok {
		_spec.SetField(entsession.FieldAppliedSystemCommands, field.TypeJSON, value)
		_node.AppliedSystemCommands = value
	}
	if value, ok := _c.mutation.LastRunAt(); ok {
		_spec.SetField(entsession.FieldLastRunAt, field.TypeTime, value)
		_node.LastRunAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(entsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(entsession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ClosedAt(); ok {
		_spec.SetField(entsession.FieldClosedAt, field.TypeTime, value)
		_node.ClosedAt = &value
	}
	return _node, _spec
}

// SessionCreateBulk is the builder for creating many Session entities in bulk.
type SessionCreateBulk struct {
	config
	err      error
	builders []*SessionCreate
}

// Save creates the Session entities in the database.
func (_c *SessionCreateBulk) Save(ctx context.Context) ([]*Session, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Session, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionCreateBulk) SaveX(ctx context.Context) []*Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
