// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/sessionsideevent"
)

// SessionSideEventCreate is the builder for creating a SessionSideEvent entity.
type SessionSideEventCreate struct {
	config
	mutation *SessionSideEventMutation
	hooks    []Hook
}

// SetSideID sets the "side_id" field.
func (_c *SessionSideEventCreate) SetSideID(v string) *SessionSideEventCreate {
	_c.mutation.SetSideID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *SessionSideEventCreate) SetSessionID(v string) *SessionSideEventCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetProcessRunID sets the "process_run_id" field.
func (_c *SessionSideEventCreate) SetProcessRunID(v string) *SessionSideEventCreate {
	_c.mutation.SetProcessRunID(v)
	return _c
}

// SetEventID sets the "event_id" field.
func (_c *SessionSideEventCreate) SetEventID(v string) *SessionSideEventCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *SessionSideEventCreate) SetType(v string) *SessionSideEventCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetCorrelationID sets the "correlation_id" field.
func (_c *SessionSideEventCreate) SetCorrelationID(v string) *SessionSideEventCreate {
	_c.mutation.SetCorrelationID(v)
	return _c
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (_c *SessionSideEventCreate) SetNillableCorrelationID(v *string) *SessionSideEventCreate {
	if v != nil {
		_c.SetCorrelationID(*v)
	}
	return _c
}

// SetTurnID sets the "turn_id" field.
func (_c *SessionSideEventCreate) SetTurnID(v string) *SessionSideEventCreate {
	_c.mutation.SetTurnID(v)
	return _c
}

// SetNillableTurnID sets the "turn_id" field if the given value is not nil.
func (_c *SessionSideEventCreate) SetNillableTurnID(v *string) *SessionSideEventCreate {
	if v != nil {
		_c.SetTurnID(*v)
	}
	return _c
}

// SetPhase sets the "phase" field.
func (_c *SessionSideEventCreate) SetPhase(v string) *SessionSideEventCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_c *SessionSideEventCreate) SetNillablePhase(v *string) *SessionSideEventCreate {
	if v != nil {
		_c.SetPhase(*v)
	}
	return _c
}

// SetContentKind sets the "content_kind" field.
func (_c *SessionSideEventCreate) SetContentKind(v string) *SessionSideEventCreate {
	_c.mutation.SetContentKind(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *SessionSideEventCreate) SetContent(v map[string]interface{}) *SessionSideEventCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetTurnIndex sets the "turn_index" field.
func (_c *SessionSideEventCreate) SetTurnIndex(v int) *SessionSideEventCreate {
	_c.mutation.SetTurnIndex(v)
	return _c
}

// SetSequence sets the "sequence" field.
func (_c *SessionSideEventCreate) SetSequence(v int64) *SessionSideEventCreate {
	_c.mutation.SetSequence(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SessionSideEventCreate) SetCreatedAt(v time.Time) *SessionSideEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SessionSideEventCreate) SetNillableCreatedAt(v *time.Time) *SessionSideEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SessionSideEventCreate) SetID(v string) *SessionSideEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SessionSideEventMutation object of the builder.
func (_c *SessionSideEventCreate) Mutation() *SessionSideEventMutation {
	return _c.mutation
}

// Save creates the SessionSideEvent in the database.
func (_c *SessionSideEventCreate) Save(ctx context.Context) (*SessionSideEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionSideEventCreate) SaveX(ctx context.Context) *SessionSideEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionSideEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionSideEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SessionSideEventCreate) defaults() {
	if _, ok := _c.mutation.CorrelationID(); !ok {
		v := sessionsideevent.DefaultCorrelationID
		_c.mutation.SetCorrelationID(v)
	}
	if _, ok := _c.mutation.TurnID(); !ok {
		v := sessionsideevent.DefaultTurnID
		_c.mutation.SetTurnID(v)
	}
	if _, ok := _c.mutation.Phase(); !ok {
		v := sessionsideevent.DefaultPhase
		_c.mutation.SetPhase(v)
	}
	if _, ok := _c.mutation.Content(); !ok {
		v := sessionsideevent.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sessionsideevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionSideEventCreate) check() error {
	if _, ok := _c.mutation.SideID(); !ok {
		return &ValidationError{Name: "side_id", err: errors.New(`ent: missing required field "SessionSideEvent.side_id"`)}
	}
	if v, ok := _c.mutation.SideID(); ok {
		if err := sessionsideevent.SideIDValidator(v); err != nil {
			return &ValidationError{Name: "side_id", err: fmt.Errorf(`ent: validator failed for field "SessionSideEvent.side_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "SessionSideEvent.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := sessionsideevent.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "SessionSideEvent.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProcessRunID(); !ok {
		return &ValidationError{Name: "process_run_id", err: errors.New(`ent: missing required field "SessionSideEvent.process_run_id"`)}
	}
	if v, ok := _c.mutation.ProcessRunID(); ok {
		if err := sessionsideevent.ProcessRunIDValidator(v); err != nil {
			return &ValidationError{Name: "process_run_id", err: fmt.Errorf(`ent: validator failed for field "SessionSideEvent.process_run_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "SessionSideEvent.event_id"`)}
	}
	if v, ok := _c.mutation.EventID(); ok {
		if err := sessionsideevent.EventIDValidator(v); err != nil {
			return &ValidationError{Name: "event_id", err: fmt.Errorf(`ent: validator failed for field "SessionSideEvent.event_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "SessionSideEvent.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := sessionsideevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SessionSideEvent.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CorrelationID(); !ok {
		return &ValidationError{Name: "correlation_id", err: errors.New(`ent: missing required field "SessionSideEvent.correlation_id"`)}
	}
	if _, ok := _c.mutation.TurnID(); !ok {
		return &ValidationError{Name: "turn_id", err: errors.New(`ent: missing required field "SessionSideEvent.turn_id"`)}
	}
	if _, ok := _c.mutation.Phase(); !ok {
		return &ValidationError{Name: "phase", err: errors.New(`ent: missing required field "SessionSideEvent.phase"`)}
	}
	if _, ok := _c.mutation.ContentKind(); !ok {
		return &ValidationError{Name: "content_kind", err: errors.New(`ent: missing required field "SessionSideEvent.content_kind"`)}
	}
	if v, ok := _c.mutation.ContentKind(); ok {
		if err := sessionsideevent.ContentKindValidator(v); err != nil {
			return &ValidationError{Name: "content_kind", err: fmt.Errorf(`ent: validator failed for field "SessionSideEvent.content_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "SessionSideEvent.content"`)}
	}
	if _, ok := _c.mutation.TurnIndex(); !ok {
		return &ValidationError{Name: "turn_index", err: errors.New(`ent: missing required field "SessionSideEvent.turn_index"`)}
	}
	if v, ok := _c.mutation.TurnIndex(); ok {
		if err := sessionsideevent.TurnIndexValidator(v); err != nil {
			return &ValidationError{Name: "turn_index", err: fmt.Errorf(`ent: validator failed for field "SessionSideEvent.turn_index": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sequence(); !ok {
		return &ValidationError{Name: "sequence", err: errors.New(`ent: missing required field "SessionSideEvent.sequence"`)}
	}
	if v, ok := _c.mutation.Sequence(); ok {
		if err := sessionsideevent.SequenceValidator(v); err != nil {
			return &ValidationError{Name: "sequence", err: fmt.Errorf(`ent: validator failed for field "SessionSideEvent.sequence": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SessionSideEvent.created_at"`)}
	}
	return nil
}

func (_c *SessionSideEventCreate) sqlSave(ctx context.Context) (*SessionSideEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SessionSideEvent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionSideEventCreate) createSpec() (*SessionSideEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &SessionSideEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sessionsideevent.Table, sqlgraph.NewFieldSpec(sessionsideevent.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SideID(); ok {
		_spec.SetField(sessionsideevent.FieldSideID, field.TypeString, value)
		_node.SideID = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(sessionsideevent.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.ProcessRunID(); ok {
		_spec.SetField(sessionsideevent.FieldProcessRunID, field.TypeString, value)
		_node.ProcessRunID = value
	}
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(sessionsideevent.FieldEventID, field.TypeString, value)
		_node.EventID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(sessionsideevent.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.CorrelationID(); ok {
		_spec.SetField(sessionsideevent.FieldCorrelationID, field.TypeString, value)
		_node.CorrelationID = value
	}
	if value, ok := _c.mutation.TurnID(); ok {
		_spec.SetField(sessionsideevent.FieldTurnID, field.TypeString, value)
		_node.TurnID = value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(sessionsideevent.FieldPhase, field.TypeString, value)
		_node.Phase = value
	}
	if value, ok := _c.mutation.ContentKind(); ok {
		_spec.SetField(sessionsideevent.FieldContentKind, field.TypeString, value)
		_node.ContentKind = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(sessionsideevent.FieldContent, field.TypeJSON, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.TurnIndex(); ok {
		_spec.SetField(sessionsideevent.FieldTurnIndex, field.TypeInt, value)
		_node.TurnIndex = value
	}
	if value, ok := _c.mutation.Sequence(); ok {
		_spec.SetField(sessionsideevent.FieldSequence, field.TypeInt64, value)
		_node.Sequence = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sessionsideevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// SessionSideEventCreateBulk is the builder for creating many SessionSideEvent entities in bulk.
type SessionSideEventCreateBulk struct {
	config
	err      error
	builders []*SessionSideEventCreate
}

// Save creates the SessionSideEvent entities in the database.
func (_c *SessionSideEventCreateBulk) Save(ctx context.Context) ([]*SessionSideEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SessionSideEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionSideEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionSideEventCreateBulk) SaveX(ctx context.Context) []*SessionSideEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionSideEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionSideEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
