// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nzlov/anycode/internal/domain/session"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/predicate"
	entsession "github.com/nzlov/anycode/internal/infra/entstore/ent/session"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *SessionUpdate) SetProjectID(v string) *SessionUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableProjectID(v *string) *SessionUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetRequirement sets the "requirement" field.
func (_u *SessionUpdate) SetRequirement(v string) *SessionUpdate {
	_u.mutation.SetRequirement(v)
	return _u
}

// SetNillableRequirement sets the "requirement" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableRequirement(v *string) *SessionUpdate {
	if v != nil {
		_u.SetRequirement(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *SessionUpdate) SetMode(v string) *SessionUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableMode(v *string) *SessionUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SessionUpdate) SetStatus(v string) *SessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableStatus(v *string) *SessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SessionUpdate) SetPriority(v string) *SessionUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SessionUpdate) SetNillablePriority(v *string) *SessionUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetCloseReason sets the "close_reason" field.
func (_u *SessionUpdate) SetCloseReason(v string) *SessionUpdate {
	_u.mutation.SetCloseReason(v)
	return _u
}

// SetNillableCloseReason sets the "close_reason" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCloseReason(v *string) *SessionUpdate {
	if v != nil {
		_u.SetCloseReason(*v)
	}
	return _u
}

// ClearCloseReason clears the value of the "close_reason" field.
func (_u *SessionUpdate) ClearCloseReason() *SessionUpdate {
	_u.mutation.ClearCloseReason()
	return _u
}

// SetBaseBranch sets the "base_branch" field.
func (_u *SessionUpdate) SetBaseBranch(v string) *SessionUpdate {
	_u.mutation.SetBaseBranch(v)
	return _u
}

// SetNillableBaseBranch sets the "base_branch" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableBaseBranch(v *string) *SessionUpdate {
	if v != nil {
		_u.SetBaseBranch(*v)
	}
	return _u
}

// SetWorktreePath sets the "worktree_path" field.
func (_u *SessionUpdate) SetWorktreePath(v string) *SessionUpdate {
	_u.mutation.SetWorktreePath(v)
	return _u
}

// SetNillableWorktreePath sets the "worktree_path" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableWorktreePath(v *string) *SessionUpdate {
	if v != nil {
		_u.SetWorktreePath(*v)
	}
	return _u
}

// SetCodexSessionID sets the "codex_session_id" field.
func (_u *SessionUpdate) SetCodexSessionID(v string) *SessionUpdate {
	_u.mutation.SetCodexSessionID(v)
	return _u
}

// SetNillableCodexSessionID sets the "codex_session_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCodexSessionID(v *string) *SessionUpdate {
	if v != nil {
		_u.SetCodexSessionID(*v)
	}
	return _u
}

// SetCodexModel sets the "codex_model" field.
func (_u *SessionUpdate) SetCodexModel(v string) *SessionUpdate {
	_u.mutation.SetCodexModel(v)
	return _u
}

// SetNillableCodexModel sets the "codex_model" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCodexModel(v *string) *SessionUpdate {
	if v != nil {
		_u.SetCodexModel(*v)
	}
	return _u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_u *SessionUpdate) SetReasoningEffort(v string) *SessionUpdate {
	_u.mutation.SetReasoningEffort(v)
	return _u
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableReasoningEffort(v *string) *SessionUpdate {
	if v != nil {
		_u.SetReasoningEffort(*v)
	}
	return _u
}

// SetPermissionMode sets the "permission_mode" field.
func (_u *SessionUpdate) SetPermissionMode(v string) *SessionUpdate {
	_u.mutation.SetPermissionMode(v)
	return _u
}

// SetNillablePermissionMode sets the "permission_mode" field if the given value is not nil.
func (_u *SessionUpdate) SetNillablePermissionMode(v *string) *SessionUpdate {
	if v != nil {
		_u.SetPermissionMode(*v)
	}
	return _u
}

// SetTodoList sets the "todo_list" field.
func (_u *SessionUpdate) SetTodoList(v session.TodoList) *SessionUpdate {
	_u.mutation.SetTodoList(v)
	return _u
}

// SetNillableTodoList sets the "todo_list" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableTodoList(v *session.TodoList) *SessionUpdate {
	if v != nil {
		_u.SetTodoList(*v)
	}
	return _u
}

// ClearTodoList clears the value of the "todo_list" field.
func (_u *SessionUpdate) ClearTodoList() *SessionUpdate {
	_u.mutation.ClearTodoList()
	return _u
}

// SetQueuedAt sets the "queued_at" field.
func (_u *SessionUpdate) SetQueuedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetQueuedAt(v)
	return _u
}

// SetNillableQueuedAt sets the "queued_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableQueuedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetQueuedAt(*v)
	}
	return _u
}

// ClearQueuedAt clears the value of the "queued_at" field.
func (_u *SessionUpdate) ClearQueuedAt() *SessionUpdate {
	_u.mutation.ClearQueuedAt()
	return _u
}

// SetQueueKind sets the "queue_kind" field.
func (_u *SessionUpdate) SetQueueKind(v string) *SessionUpdate {
	_u.mutation.SetQueueKind(v)
	return _u
}

// SetNillableQueueKind sets the "queue_kind" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableQueueKind(v *string) *SessionUpdate {
	if v != nil {
		_u.SetQueueKind(*v)
	}
	return _u
}

// SetQueuePriority sets the "queue_priority" field.
func (_u *SessionUpdate) SetQueuePriority(v string) *SessionUpdate {
	_u.mutation.SetQueuePriority(v)
	return _u
}

// SetNillableQueuePriority sets the "queue_priority" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableQueuePriority(v *string) *SessionUpdate {
	if v != nil {
		_u.SetQueuePriority(*v)
	}
	return _u
}

// SetQueueWorkflowRunID sets the "queue_workflow_run_id" field.
func (_u *SessionUpdate) SetQueueWorkflowRunID(v string) *SessionUpdate {
	_u.mutation.SetQueueWorkflowRunID(v)
	return _u
}

// SetNillableQueueWorkflowRunID sets the "queue_workflow_run_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableQueueWorkflowRunID(v *string) *SessionUpdate {
	if v != nil {
		_u.SetQueueWorkflowRunID(*v)
	}
	return _u
}

// SetQueueNodeRunID sets the "queue_node_run_id" field.
func (_u *SessionUpdate) SetQueueNodeRunID(v string) *SessionUpdate {
	_u.mutation.SetQueueNodeRunID(v)
	return _u
}

// SetNillableQueueNodeRunID sets the "queue_node_run_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableQueueNodeRunID(v *string) *SessionUpdate {
	if v != nil {
		_u.SetQueueNodeRunID(*v)
	}
	return _u
}

// SetQueuePrompt sets the "queue_prompt" field.
func (_u *SessionUpdate) SetQueuePrompt(v string) *SessionUpdate {
	_u.mutation.SetQueuePrompt(v)
	return _u
}

// SetNillableQueuePrompt sets the "queue_prompt" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableQueuePrompt(v *string) *SessionUpdate {
	if v != nil {
		_u.SetQueuePrompt(*v)
	}
	return _u
}

// SetQueueResumeCodexSessionID sets the "queue_resume_codex_session_id" field.
func (_u *SessionUpdate) SetQueueResumeCodexSessionID(v string) *SessionUpdate {
	_u.mutation.SetQueueResumeCodexSessionID(v)
	return _u
}

// SetNillableQueueResumeCodexSessionID sets the "queue_resume_codex_session_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableQueueResumeCodexSessionID(v *string) *SessionUpdate {
	if v != nil {
		_u.SetQueueResumeCodexSessionID(*v)
	}
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *SessionUpdate) SetLastRunAt(v time.Time) *SessionUpdate {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableLastRunAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *SessionUpdate) ClearLastRunAt() *SessionUpdate {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SessionUpdate) SetUpdatedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *SessionUpdate) SetClosedAt(v time.Time) *SessionUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableClosedAt(v *time.Time) *SessionUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *SessionUpdate) ClearClosedAt() *SessionUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdate) check() error {
	if v, ok := _u.mutation.ProjectID(); ok {
		if err := entsession.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "Session.project_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := entsession.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Session.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := entsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Session.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entsession.Table, entsession.Columns, sqlgraph.NewFieldSpec(entsession.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(entsession.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Requirement(); ok {
		_spec.SetField(entsession.FieldRequirement, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(entsession.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(entsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(entsession.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.CloseReason(); ok {
		_spec.SetField(entsession.FieldCloseReason, field.TypeString, value)
	}
	if _u.mutation.CloseReasonCleared() {
		_spec.ClearField(entsession.FieldCloseReason, field.TypeString)
	}
	if value, ok := _u.mutation.BaseBranch(); ok {
		_spec.SetField(entsession.FieldBaseBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorktreePath(); ok {
		_spec.SetField(entsession.FieldWorktreePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodexSessionID(); ok {
		_spec.SetField(entsession.FieldCodexSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodexModel(); ok {
		_spec.SetField(entsession.FieldCodexModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReasoningEffort(); ok {
		_spec.SetField(entsession.FieldReasoningEffort, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermissionMode(); ok {
		_spec.SetField(entsession.FieldPermissionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.TodoList(); ok {
		_spec.SetField(entsession.FieldTodoList, field.TypeJSON, value)
	}
	if _u.mutation.TodoListCleared() {
		_spec.ClearField(entsession.FieldTodoList, field.TypeJSON)
	}
	if value, ok := _u.mutation.QueuedAt(); ok {
		_spec.SetField(entsession.FieldQueuedAt, field.TypeTime, value)
	}
	if _u.mutation.QueuedAtCleared() {
		_spec.ClearField(entsession.FieldQueuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.QueueKind(); ok {
		_spec.SetField(entsession.FieldQueueKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.QueuePriority(); ok {
		_spec.SetField(entsession.FieldQueuePriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.QueueWorkflowRunID(); ok {
		_spec.SetField(entsession.FieldQueueWorkflowRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.QueueNodeRunID(); ok {
		_spec.SetField(entsession.FieldQueueNodeRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.QueuePrompt(); ok {
		_spec.SetField(entsession.FieldQueuePrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.QueueResumeCodexSessionID(); ok {
		_spec.SetField(entsession.FieldQueueResumeCodexSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(entsession.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(entsession.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(entsession.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(entsession.FieldClosedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetProjectID sets the "project_id" field.
func (_u *SessionUpdateOne) SetProjectID(v string) *SessionUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableProjectID(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetRequirement sets the "requirement" field.
func (_u *SessionUpdateOne) SetRequirement(v string) *SessionUpdateOne {
	_u.mutation.SetRequirement(v)
	return _u
}

// SetNillableRequirement sets the "requirement" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableRequirement(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetRequirement(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *SessionUpdateOne) SetMode(v string) *SessionUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableMode(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SessionUpdateOne) SetStatus(v string) *SessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableStatus(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SessionUpdateOne) SetPriority(v string) *SessionUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillablePriority(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetCloseReason sets the "close_reason" field.
func (_u *SessionUpdateOne) SetCloseReason(v string) *SessionUpdateOne {
	_u.mutation.SetCloseReason(v)
	return _u
}

// SetNillableCloseReason sets the "close_reason" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCloseReason(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetCloseReason(*v)
	}
	return _u
}

// ClearCloseReason clears the value of the "close_reason" field.
func (_u *SessionUpdateOne) ClearCloseReason() *SessionUpdateOne {
	_u.mutation.ClearCloseReason()
	return _u
}

// SetBaseBranch sets the "base_branch" field.
func (_u *SessionUpdateOne) SetBaseBranch(v string) *SessionUpdateOne {
	_u.mutation.SetBaseBranch(v)
	return _u
}

// SetNillableBaseBranch sets the "base_branch" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableBaseBranch(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetBaseBranch(*v)
	}
	return _u
}

// SetWorktreePath sets the "worktree_path" field.
func (_u *SessionUpdateOne) SetWorktreePath(v string) *SessionUpdateOne {
	_u.mutation.SetWorktreePath(v)
	return _u
}

// SetNillableWorktreePath sets the "worktree_path" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableWorktreePath(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetWorktreePath(*v)
	}
	return _u
}

// SetCodexSessionID sets the "codex_session_id" field.
func (_u *SessionUpdateOne) SetCodexSessionID(v string) *SessionUpdateOne {
	_u.mutation.SetCodexSessionID(v)
	return _u
}

// SetNillableCodexSessionID sets the "codex_session_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCodexSessionID(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetCodexSessionID(*v)
	}
	return _u
}

// SetCodexModel sets the "codex_model" field.
func (_u *SessionUpdateOne) SetCodexModel(v string) *SessionUpdateOne {
	_u.mutation.SetCodexModel(v)
	return _u
}

// SetNillableCodexModel sets the "codex_model" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCodexModel(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetCodexModel(*v)
	}
	return _u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_u *SessionUpdateOne) SetReasoningEffort(v string) *SessionUpdateOne {
	_u.mutation.SetReasoningEffort(v)
	return _u
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableReasoningEffort(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetReasoningEffort(*v)
	}
	return _u
}

// SetPermissionMode sets the "permission_mode" field.
func (_u *SessionUpdateOne) SetPermissionMode(v string) *SessionUpdateOne {
	_u.mutation.SetPermissionMode(v)
	return _u
}

// SetNillablePermissionMode sets the "permission_mode" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillablePermissionMode(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetPermissionMode(*v)
	}
	return _u
}

// SetTodoList sets the "todo_list" field.
func (_u *SessionUpdateOne) SetTodoList(v session.TodoList) *SessionUpdateOne {
	_u.mutation.SetTodoList(v)
	return _u
}

// SetNillableTodoList sets the "todo_list" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableTodoList(v *session.TodoList) *SessionUpdateOne {
	if v != nil {
		_u.SetTodoList(*v)
	}
	return _u
}

// ClearTodoList clears the value of the "todo_list" field.
func (_u *SessionUpdateOne) ClearTodoList() *SessionUpdateOne {
	_u.mutation.ClearTodoList()
	return _u
}

// SetQueuedAt sets the "queued_at" field.
func (_u *SessionUpdateOne) SetQueuedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetQueuedAt(v)
	return _u
}

// SetNillableQueuedAt sets the "queued_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableQueuedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetQueuedAt(*v)
	}
	return _u
}

// ClearQueuedAt clears the value of the "queued_at" field.
func (_u *SessionUpdateOne) ClearQueuedAt() *SessionUpdateOne {
	_u.mutation.ClearQueuedAt()
	return _u
}

// SetQueueKind sets the "queue_kind" field.
func (_u *SessionUpdateOne) SetQueueKind(v string) *SessionUpdateOne {
	_u.mutation.SetQueueKind(v)
	return _u
}

// SetNillableQueueKind sets the "queue_kind" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableQueueKind(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetQueueKind(*v)
	}
	return _u
}

// SetQueuePriority sets the "queue_priority" field.
func (_u *SessionUpdateOne) SetQueuePriority(v string) *SessionUpdateOne {
	_u.mutation.SetQueuePriority(v)
	return _u
}

// SetNillableQueuePriority sets the "queue_priority" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableQueuePriority(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetQueuePriority(*v)
	}
	return _u
}

// SetQueueWorkflowRunID sets the "queue_workflow_run_id" field.
func (_u *SessionUpdateOne) SetQueueWorkflowRunID(v string) *SessionUpdateOne {
	_u.mutation.SetQueueWorkflowRunID(v)
	return _u
}

// SetNillableQueueWorkflowRunID sets the "queue_workflow_run_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableQueueWorkflowRunID(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetQueueWorkflowRunID(*v)
	}
	return _u
}

// SetQueueNodeRunID sets the "queue_node_run_id" field.
func (_u *SessionUpdateOne) SetQueueNodeRunID(v string) *SessionUpdateOne {
	_u.mutation.SetQueueNodeRunID(v)
	return _u
}

// SetNillableQueueNodeRunID sets the "queue_node_run_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableQueueNodeRunID(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetQueueNodeRunID(*v)
	}
	return _u
}

// SetQueuePrompt sets the "queue_prompt" field.
func (_u *SessionUpdateOne) SetQueuePrompt(v string) *SessionUpdateOne {
	_u.mutation.SetQueuePrompt(v)
	return _u
}

// SetNillableQueuePrompt sets the "queue_prompt" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableQueuePrompt(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetQueuePrompt(*v)
	}
	return _u
}

// SetQueueResumeCodexSessionID sets the "queue_resume_codex_session_id" field.
func (_u *SessionUpdateOne) SetQueueResumeCodexSessionID(v string) *SessionUpdateOne {
	_u.mutation.SetQueueResumeCodexSessionID(v)
	return _u
}

// SetNillableQueueResumeCodexSessionID sets the "queue_resume_codex_session_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableQueueResumeCodexSessionID(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetQueueResumeCodexSessionID(*v)
	}
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *SessionUpdateOne) SetLastRunAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableLastRunAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *SessionUpdateOne) ClearLastRunAt() *SessionUpdateOne {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SessionUpdateOne) SetUpdatedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *SessionUpdateOne) SetClosedAt(v time.Time) *SessionUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableClosedAt(v *time.Time) *SessionUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *SessionUpdateOne) ClearClosedAt() *SessionUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdateOne) check() error {
	if v, ok := _u.mutation.ProjectID(); ok {
		if err := entsession.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "Session.project_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := entsession.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "Session.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := entsession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Session.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entsession.Table, entsession.Columns, sqlgraph.NewFieldSpec(entsession.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entsession.FieldID)
		for _, f := range fields {
			if !entsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(entsession.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Requirement(); ok {
		_spec.SetField(entsession.FieldRequirement, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(entsession.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(entsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(entsession.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.CloseReason(); ok {
		_spec.SetField(entsession.FieldCloseReason, field.TypeString, value)
	}
	if _u.mutation.CloseReasonCleared() {
		_spec.ClearField(entsession.FieldCloseReason, field.TypeString)
	}
	if value, ok := _u.mutation.BaseBranch(); ok {
		_spec.SetField(entsession.FieldBaseBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorktreePath(); ok {
		_spec.SetField(entsession.FieldWorktreePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodexSessionID(); ok {
		_spec.SetField(entsession.FieldCodexSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodexModel(); ok {
		_spec.SetField(entsession.FieldCodexModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReasoningEffort(); ok {
		_spec.SetField(entsession.FieldReasoningEffort, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermissionMode(); ok {
		_spec.SetField(entsession.FieldPermissionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.TodoList(); ok {
		_spec.SetField(entsession.FieldTodoList, field.TypeJSON, value)
	}
	if _u.mutation.TodoListCleared() {
		_spec.ClearField(entsession.FieldTodoList, field.TypeJSON)
	}
	if value, ok := _u.mutation.QueuedAt(); ok {
		_spec.SetField(entsession.FieldQueuedAt, field.TypeTime, value)
	}
	if _u.mutation.QueuedAtCleared() {
		_spec.ClearField(entsession.FieldQueuedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.QueueKind(); ok {
		_spec.SetField(entsession.FieldQueueKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.QueuePriority(); ok {
		_spec.SetField(entsession.FieldQueuePriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.QueueWorkflowRunID(); ok {
		_spec.SetField(entsession.FieldQueueWorkflowRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.QueueNodeRunID(); ok {
		_spec.SetField(entsession.FieldQueueNodeRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.QueuePrompt(); ok {
		_spec.SetField(entsession.FieldQueuePrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.QueueResumeCodexSessionID(); ok {
		_spec.SetField(entsession.FieldQueueResumeCodexSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(entsession.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(entsession.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(entsession.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(entsession.FieldClosedAt, field.TypeTime)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
