// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/predicate"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/sessionattachment"
)

// SessionAttachmentUpdate is the builder for updating SessionAttachment entities.
type SessionAttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *SessionAttachmentMutation
}

// Where appends a list predicates to the SessionAttachmentUpdate builder.
func (_u *SessionAttachmentUpdate) Where(ps ...predicate.SessionAttachment) *SessionAttachmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *SessionAttachmentUpdate) SetSessionID(v string) *SessionAttachmentUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *SessionAttachmentUpdate) SetNillableSessionID(v *string) *SessionAttachmentUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *SessionAttachmentUpdate) SetSourceType(v string) *SessionAttachmentUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *SessionAttachmentUpdate) SetNillableSourceType(v *string) *SessionAttachmentUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *SessionAttachmentUpdate) SetSourceID(v string) *SessionAttachmentUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *SessionAttachmentUpdate) SetNillableSourceID(v *string) *SessionAttachmentUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *SessionAttachmentUpdate) SetKind(v string) *SessionAttachmentUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SessionAttachmentUpdate) SetNillableKind(v *string) *SessionAttachmentUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetFilename sets the "filename" field.
func (_u *SessionAttachmentUpdate) SetFilename(v string) *SessionAttachmentUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *SessionAttachmentUpdate) SetNillableFilename(v *string) *SessionAttachmentUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *SessionAttachmentUpdate) SetPath(v string) *SessionAttachmentUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *SessionAttachmentUpdate) SetNillablePath(v *string) *SessionAttachmentUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *SessionAttachmentUpdate) SetMimeType(v string) *SessionAttachmentUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *SessionAttachmentUpdate) SetNillableMimeType(v *string) *SessionAttachmentUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *SessionAttachmentUpdate) SetSize(v int64) *SessionAttachmentUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *SessionAttachmentUpdate) SetNillableSize(v *int64) *SessionAttachmentUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *SessionAttachmentUpdate) AddSize(v int64) *SessionAttachmentUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetPreviewable sets the "previewable" field.
func (_u *SessionAttachmentUpdate) SetPreviewable(v bool) *SessionAttachmentUpdate {
	_u.mutation.SetPreviewable(v)
	return _u
}

// SetNillablePreviewable sets the "previewable" field if the given value is not nil.
func (_u *SessionAttachmentUpdate) SetNillablePreviewable(v *bool) *SessionAttachmentUpdate {
	if v != nil {
		_u.SetPreviewable(*v)
	}
	return _u
}

// Mutation returns the SessionAttachmentMutation object of the builder.
func (_u *SessionAttachmentUpdate) Mutation() *SessionAttachmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionAttachmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionAttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionAttachmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionAttachmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionAttachmentUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := sessionattachment.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "SessionAttachment.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := sessionattachment.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "SessionAttachment.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceID(); ok {
		if err := sessionattachment.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "SessionAttachment.source_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Filename(); ok {
		if err := sessionattachment.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "SessionAttachment.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := sessionattachment.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "SessionAttachment.path": %w`, err)}
		}
	}
	return nil
}

func (_u *SessionAttachmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sessionattachment.Table, sessionattachment.Columns, sqlgraph.NewFieldSpec(sessionattachment.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(sessionattachment.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(sessionattachment.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(sessionattachment.FieldSourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(sessionattachment.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(sessionattachment.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(sessionattachment.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(sessionattachment.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(sessionattachment.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(sessionattachment.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Previewable(); ok {
		_spec.SetField(sessionattachment.FieldPreviewable, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sessionattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionAttachmentUpdateOne is the builder for updating a single SessionAttachment entity.
type SessionAttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionAttachmentMutation
}

// SetSessionID sets the "session_id" field.
func (_u *SessionAttachmentUpdateOne) SetSessionID(v string) *SessionAttachmentUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *SessionAttachmentUpdateOne) SetNillableSessionID(v *string) *SessionAttachmentUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *SessionAttachmentUpdateOne) SetSourceType(v string) *SessionAttachmentUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *SessionAttachmentUpdateOne) SetNillableSourceType(v *string) *SessionAttachmentUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *SessionAttachmentUpdateOne) SetSourceID(v string) *SessionAttachmentUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *SessionAttachmentUpdateOne) SetNillableSourceID(v *string) *SessionAttachmentUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *SessionAttachmentUpdateOne) SetKind(v string) *SessionAttachmentUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SessionAttachmentUpdateOne) SetNillableKind(v *string) *SessionAttachmentUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetFilename sets the "filename" field.
func (_u *SessionAttachmentUpdateOne) SetFilename(v string) *SessionAttachmentUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *SessionAttachmentUpdateOne) SetNillableFilename(v *string) *SessionAttachmentUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *SessionAttachmentUpdateOne) SetPath(v string) *SessionAttachmentUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *SessionAttachmentUpdateOne) SetNillablePath(v *string) *SessionAttachmentUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *SessionAttachmentUpdateOne) SetMimeType(v string) *SessionAttachmentUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *SessionAttachmentUpdateOne) SetNillableMimeType(v *string) *SessionAttachmentUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *SessionAttachmentUpdateOne) SetSize(v int64) *SessionAttachmentUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *SessionAttachmentUpdateOne) SetNillableSize(v *int64) *SessionAttachmentUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *SessionAttachmentUpdateOne) AddSize(v int64) *SessionAttachmentUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetPreviewable sets the "previewable" field.
func (_u *SessionAttachmentUpdateOne) SetPreviewable(v bool) *SessionAttachmentUpdateOne {
	_u.mutation.SetPreviewable(v)
	return _u
}

// SetNillablePreviewable sets the "previewable" field if the given value is not nil.
func (_u *SessionAttachmentUpdateOne) SetNillablePreviewable(v *bool) *SessionAttachmentUpdateOne {
	if v != nil {
		_u.SetPreviewable(*v)
	}
	return _u
}

// Mutation returns the SessionAttachmentMutation object of the builder.
func (_u *SessionAttachmentUpdateOne) Mutation() *SessionAttachmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the SessionAttachmentUpdate builder.
func (_u *SessionAttachmentUpdateOne) Where(ps ...predicate.SessionAttachment) *SessionAttachmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionAttachmentUpdateOne) Select(field string, fields ...string) *SessionAttachmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SessionAttachment entity.
func (_u *SessionAttachmentUpdateOne) Save(ctx context.Context) (*SessionAttachment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionAttachmentUpdateOne) SaveX(ctx context.Context) *SessionAttachment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionAttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionAttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionAttachmentUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := sessionattachment.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "SessionAttachment.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := sessionattachment.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "SessionAttachment.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceID(); ok {
		if err := sessionattachment.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "SessionAttachment.source_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Filename(); ok {
		if err := sessionattachment.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "SessionAttachment.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := sessionattachment.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "SessionAttachment.path": %w`, err)}
		}
	}
	return nil
}

func (_u *SessionAttachmentUpdateOne) sqlSave(ctx context.Context) (_node *SessionAttachment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sessionattachment.Table, sessionattachment.Columns, sqlgraph.NewFieldSpec(sessionattachment.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SessionAttachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sessionattachment.FieldID)
		for _, f := range fields {
			if !sessionattachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sessionattachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(sessionattachment.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(sessionattachment.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(sessionattachment.FieldSourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(sessionattachment.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(sessionattachment.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(sessionattachment.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(sessionattachment.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(sessionattachment.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(sessionattachment.FieldSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Previewable(); ok {
		_spec.SetField(sessionattachment.FieldPreviewable, field.TypeBool, value)
	}
	_node = &SessionAttachment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sessionattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
