// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/stagedattachment"
)

// StagedAttachment is the model entity for the StagedAttachment schema.
type StagedAttachment struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// OwnerKeyHash holds the value of the "owner_key_hash" field.
	OwnerKeyHash string `json:"owner_key_hash,omitempty"`
	// Filename holds the value of the "filename" field.
	Filename string `json:"filename,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// Size holds the value of the "size" field.
	Size int64 `json:"size,omitempty"`
	// Previewable holds the value of the "previewable" field.
	Previewable bool `json:"previewable,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StagedAttachment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stagedattachment.FieldPreviewable:
			values[i] = new(sql.NullBool)
		case stagedattachment.FieldSize:
			values[i] = new(sql.NullInt64)
		case stagedattachment.FieldID, stagedattachment.FieldOwnerKeyHash, stagedattachment.FieldFilename, stagedattachment.FieldPath, stagedattachment.FieldMimeType:
			values[i] = new(sql.NullString)
		case stagedattachment.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StagedAttachment fields.
func (_m *StagedAttachment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stagedattachment.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case stagedattachment.FieldOwnerKeyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_key_hash", values[i])
			} else if value.Valid {
				_m.OwnerKeyHash = value.String
			}
		case stagedattachment.FieldFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field filename", values[i])
			} else if value.Valid {
				_m.Filename = value.String
			}
		case stagedattachment.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case stagedattachment.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case stagedattachment.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.Int64
			}
		case stagedattachment.FieldPreviewable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field previewable", values[i])
			} else if value.Valid {
				_m.Previewable = value.Bool
			}
		case stagedattachment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StagedAttachment.
// This includes values selected through modifiers, order, etc.
func (_m *StagedAttachment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this StagedAttachment.
// Note that you need to call StagedAttachment.Unwrap() before calling this method if this StagedAttachment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StagedAttachment) Update() *StagedAttachmentUpdateOne {
	return NewStagedAttachmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StagedAttachment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StagedAttachment) Unwrap() *StagedAttachment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StagedAttachment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StagedAttachment) String() string {
	var builder strings.Builder
	builder.WriteString("StagedAttachment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("owner_key_hash=")
	builder.WriteString(_m.OwnerKeyHash)
	builder.WriteString(", ")
	builder.WriteString("filename=")
	builder.WriteString(_m.Filename)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("previewable=")
	builder.WriteString(fmt.Sprintf("%v", _m.Previewable))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StagedAttachments is a parsable slice of StagedAttachment.
type StagedAttachments []*StagedAttachment
