// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/predicate"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/systemconfiguration"
)

// SystemConfigurationUpdate is the builder for updating SystemConfiguration entities.
type SystemConfigurationUpdate struct {
	config
	hooks    []Hook
	mutation *SystemConfigurationMutation
}

// Where appends a list predicates to the SystemConfigurationUpdate builder.
func (_u *SystemConfigurationUpdate) Where(ps ...predicate.SystemConfiguration) *SystemConfigurationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWallpaperColorScheme sets the "wallpaper_color_scheme" field.
func (_u *SystemConfigurationUpdate) SetWallpaperColorScheme(v string) *SystemConfigurationUpdate {
	_u.mutation.SetWallpaperColorScheme(v)
	return _u
}

// SetNillableWallpaperColorScheme sets the "wallpaper_color_scheme" field if the given value is not nil.
func (_u *SystemConfigurationUpdate) SetNillableWallpaperColorScheme(v *string) *SystemConfigurationUpdate {
	if v != nil {
		_u.SetWallpaperColorScheme(*v)
	}
	return _u
}

// SetBackgroundType sets the "background_type" field.
func (_u *SystemConfigurationUpdate) SetBackgroundType(v string) *SystemConfigurationUpdate {
	_u.mutation.SetBackgroundType(v)
	return _u
}

// SetNillableBackgroundType sets the "background_type" field if the given value is not nil.
func (_u *SystemConfigurationUpdate) SetNillableBackgroundType(v *string) *SystemConfigurationUpdate {
	if v != nil {
		_u.SetBackgroundType(*v)
	}
	return _u
}

// SetSolidTheme sets the "solid_theme" field.
func (_u *SystemConfigurationUpdate) SetSolidTheme(v string) *SystemConfigurationUpdate {
	_u.mutation.SetSolidTheme(v)
	return _u
}

// SetNillableSolidTheme sets the "solid_theme" field if the given value is not nil.
func (_u *SystemConfigurationUpdate) SetNillableSolidTheme(v *string) *SystemConfigurationUpdate {
	if v != nil {
		_u.SetSolidTheme(*v)
	}
	return _u
}

// SetBackgroundMask sets the "background_mask" field.
func (_u *SystemConfigurationUpdate) SetBackgroundMask(v int) *SystemConfigurationUpdate {
	_u.mutation.ResetBackgroundMask()
	_u.mutation.SetBackgroundMask(v)
	return _u
}

// SetNillableBackgroundMask sets the "background_mask" field if the given value is not nil.
func (_u *SystemConfigurationUpdate) SetNillableBackgroundMask(v *int) *SystemConfigurationUpdate {
	if v != nil {
		_u.SetBackgroundMask(*v)
	}
	return _u
}

// AddBackgroundMask adds value to the "background_mask" field.
func (_u *SystemConfigurationUpdate) AddBackgroundMask(v int) *SystemConfigurationUpdate {
	_u.mutation.AddBackgroundMask(v)
	return _u
}

// SetWallpaperID sets the "wallpaper_id" field.
func (_u *SystemConfigurationUpdate) SetWallpaperID(v string) *SystemConfigurationUpdate {
	_u.mutation.SetWallpaperID(v)
	return _u
}

// SetNillableWallpaperID sets the "wallpaper_id" field if the given value is not nil.
func (_u *SystemConfigurationUpdate) SetNillableWallpaperID(v *string) *SystemConfigurationUpdate {
	if v != nil {
		_u.SetWallpaperID(*v)
	}
	return _u
}

// SetWallpaperFilename sets the "wallpaper_filename" field.
func (_u *SystemConfigurationUpdate) SetWallpaperFilename(v string) *SystemConfigurationUpdate {
	_u.mutation.SetWallpaperFilename(v)
	return _u
}

// SetNillableWallpaperFilename sets the "wallpaper_filename" field if the given value is not nil.
func (_u *SystemConfigurationUpdate) SetNillableWallpaperFilename(v *string) *SystemConfigurationUpdate {
	if v != nil {
		_u.SetWallpaperFilename(*v)
	}
	return _u
}

// SetWallpaperMimeType sets the "wallpaper_mime_type" field.
func (_u *SystemConfigurationUpdate) SetWallpaperMimeType(v string) *SystemConfigurationUpdate {
	_u.mutation.SetWallpaperMimeType(v)
	return _u
}

// SetNillableWallpaperMimeType sets the "wallpaper_mime_type" field if the given value is not nil.
func (_u *SystemConfigurationUpdate) SetNillableWallpaperMimeType(v *string) *SystemConfigurationUpdate {
	if v != nil {
		_u.SetWallpaperMimeType(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemConfigurationUpdate) SetUpdatedAt(v time.Time) *SystemConfigurationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SystemConfigurationMutation object of the builder.
func (_u *SystemConfigurationUpdate) Mutation() *SystemConfigurationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemConfigurationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemConfigurationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemConfigurationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemConfigurationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemConfigurationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemconfiguration.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemConfigurationUpdate) check() error {
	if v, ok := _u.mutation.WallpaperColorScheme(); ok {
		if err := systemconfiguration.WallpaperColorSchemeValidator(v); err != nil {
			return &ValidationError{Name: "wallpaper_color_scheme", err: fmt.Errorf(`ent: validator failed for field "SystemConfiguration.wallpaper_color_scheme": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BackgroundType(); ok {
		if err := systemconfiguration.BackgroundTypeValidator(v); err != nil {
			return &ValidationError{Name: "background_type", err: fmt.Errorf(`ent: validator failed for field "SystemConfiguration.background_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SolidTheme(); ok {
		if err := systemconfiguration.SolidThemeValidator(v); err != nil {
			return &ValidationError{Name: "solid_theme", err: fmt.Errorf(`ent: validator failed for field "SystemConfiguration.solid_theme": %w`, err)}
		}
	}
	return nil
}

func (_u *SystemConfigurationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemconfiguration.Table, systemconfiguration.Columns, sqlgraph.NewFieldSpec(systemconfiguration.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WallpaperColorScheme(); ok {
		_spec.SetField(systemconfiguration.FieldWallpaperColorScheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackgroundType(); ok {
		_spec.SetField(systemconfiguration.FieldBackgroundType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SolidTheme(); ok {
		_spec.SetField(systemconfiguration.FieldSolidTheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackgroundMask(); ok {
		_spec.SetField(systemconfiguration.FieldBackgroundMask, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBackgroundMask(); ok {
		_spec.AddField(systemconfiguration.FieldBackgroundMask, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WallpaperID(); ok {
		_spec.SetField(systemconfiguration.FieldWallpaperID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WallpaperFilename(); ok {
		_spec.SetField(systemconfiguration.FieldWallpaperFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.WallpaperMimeType(); ok {
		_spec.SetField(systemconfiguration.FieldWallpaperMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemconfiguration.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemconfiguration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemConfigurationUpdateOne is the builder for updating a single SystemConfiguration entity.
type SystemConfigurationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemConfigurationMutation
}

// SetWallpaperColorScheme sets the "wallpaper_color_scheme" field.
func (_u *SystemConfigurationUpdateOne) SetWallpaperColorScheme(v string) *SystemConfigurationUpdateOne {
	_u.mutation.SetWallpaperColorScheme(v)
	return _u
}

// SetNillableWallpaperColorScheme sets the "wallpaper_color_scheme" field if the given value is not nil.
func (_u *SystemConfigurationUpdateOne) SetNillableWallpaperColorScheme(v *string) *SystemConfigurationUpdateOne {
	if v != nil {
		_u.SetWallpaperColorScheme(*v)
	}
	return _u
}

// SetBackgroundType sets the "background_type" field.
func (_u *SystemConfigurationUpdateOne) SetBackgroundType(v string) *SystemConfigurationUpdateOne {
	_u.mutation.SetBackgroundType(v)
	return _u
}

// SetNillableBackgroundType sets the "background_type" field if the given value is not nil.
func (_u *SystemConfigurationUpdateOne) SetNillableBackgroundType(v *string) *SystemConfigurationUpdateOne {
	if v != nil {
		_u.SetBackgroundType(*v)
	}
	return _u
}

// SetSolidTheme sets the "solid_theme" field.
func (_u *SystemConfigurationUpdateOne) SetSolidTheme(v string) *SystemConfigurationUpdateOne {
	_u.mutation.SetSolidTheme(v)
	return _u
}

// SetNillableSolidTheme sets the "solid_theme" field if the given value is not nil.
func (_u *SystemConfigurationUpdateOne) SetNillableSolidTheme(v *string) *SystemConfigurationUpdateOne {
	if v != nil {
		_u.SetSolidTheme(*v)
	}
	return _u
}

// SetBackgroundMask sets the "background_mask" field.
func (_u *SystemConfigurationUpdateOne) SetBackgroundMask(v int) *SystemConfigurationUpdateOne {
	_u.mutation.ResetBackgroundMask()
	_u.mutation.SetBackgroundMask(v)
	return _u
}

// SetNillableBackgroundMask sets the "background_mask" field if the given value is not nil.
func (_u *SystemConfigurationUpdateOne) SetNillableBackgroundMask(v *int) *SystemConfigurationUpdateOne {
	if v != nil {
		_u.SetBackgroundMask(*v)
	}
	return _u
}

// AddBackgroundMask adds value to the "background_mask" field.
func (_u *SystemConfigurationUpdateOne) AddBackgroundMask(v int) *SystemConfigurationUpdateOne {
	_u.mutation.AddBackgroundMask(v)
	return _u
}

// SetWallpaperID sets the "wallpaper_id" field.
func (_u *SystemConfigurationUpdateOne) SetWallpaperID(v string) *SystemConfigurationUpdateOne {
	_u.mutation.SetWallpaperID(v)
	return _u
}

// SetNillableWallpaperID sets the "wallpaper_id" field if the given value is not nil.
func (_u *SystemConfigurationUpdateOne) SetNillableWallpaperID(v *string) *SystemConfigurationUpdateOne {
	if v != nil {
		_u.SetWallpaperID(*v)
	}
	return _u
}

// SetWallpaperFilename sets the "wallpaper_filename" field.
func (_u *SystemConfigurationUpdateOne) SetWallpaperFilename(v string) *SystemConfigurationUpdateOne {
	_u.mutation.SetWallpaperFilename(v)
	return _u
}

// SetNillableWallpaperFilename sets the "wallpaper_filename" field if the given value is not nil.
func (_u *SystemConfigurationUpdateOne) SetNillableWallpaperFilename(v *string) *SystemConfigurationUpdateOne {
	if v != nil {
		_u.SetWallpaperFilename(*v)
	}
	return _u
}

// SetWallpaperMimeType sets the "wallpaper_mime_type" field.
func (_u *SystemConfigurationUpdateOne) SetWallpaperMimeType(v string) *SystemConfigurationUpdateOne {
	_u.mutation.SetWallpaperMimeType(v)
	return _u
}

// SetNillableWallpaperMimeType sets the "wallpaper_mime_type" field if the given value is not nil.
func (_u *SystemConfigurationUpdateOne) SetNillableWallpaperMimeType(v *string) *SystemConfigurationUpdateOne {
	if v != nil {
		_u.SetWallpaperMimeType(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemConfigurationUpdateOne) SetUpdatedAt(v time.Time) *SystemConfigurationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SystemConfigurationMutation object of the builder.
func (_u *SystemConfigurationUpdateOne) Mutation() *SystemConfigurationMutation {
	return _u.mutation
}

// Where appends a list predicates to the SystemConfigurationUpdate builder.
func (_u *SystemConfigurationUpdateOne) Where(ps ...predicate.SystemConfiguration) *SystemConfigurationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemConfigurationUpdateOne) Select(field string, fields ...string) *SystemConfigurationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemConfiguration entity.
func (_u *SystemConfigurationUpdateOne) Save(ctx context.Context) (*SystemConfiguration, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemConfigurationUpdateOne) SaveX(ctx context.Context) *SystemConfiguration {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemConfigurationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemConfigurationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemConfigurationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemconfiguration.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemConfigurationUpdateOne) check() error {
	if v, ok := _u.mutation.WallpaperColorScheme(); ok {
		if err := systemconfiguration.WallpaperColorSchemeValidator(v); err != nil {
			return &ValidationError{Name: "wallpaper_color_scheme", err: fmt.Errorf(`ent: validator failed for field "SystemConfiguration.wallpaper_color_scheme": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BackgroundType(); ok {
		if err := systemconfiguration.BackgroundTypeValidator(v); err != nil {
			return &ValidationError{Name: "background_type", err: fmt.Errorf(`ent: validator failed for field "SystemConfiguration.background_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SolidTheme(); ok {
		if err := systemconfiguration.SolidThemeValidator(v); err != nil {
			return &ValidationError{Name: "solid_theme", err: fmt.Errorf(`ent: validator failed for field "SystemConfiguration.solid_theme": %w`, err)}
		}
	}
	return nil
}

func (_u *SystemConfigurationUpdateOne) sqlSave(ctx context.Context) (_node *SystemConfiguration, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemconfiguration.Table, systemconfiguration.Columns, sqlgraph.NewFieldSpec(systemconfiguration.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemConfiguration.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemconfiguration.FieldID)
		for _, f := range fields {
			if !systemconfiguration.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemconfiguration.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WallpaperColorScheme(); ok {
		_spec.SetField(systemconfiguration.FieldWallpaperColorScheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackgroundType(); ok {
		_spec.SetField(systemconfiguration.FieldBackgroundType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SolidTheme(); ok {
		_spec.SetField(systemconfiguration.FieldSolidTheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackgroundMask(); ok {
		_spec.SetField(systemconfiguration.FieldBackgroundMask, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBackgroundMask(); ok {
		_spec.AddField(systemconfiguration.FieldBackgroundMask, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WallpaperID(); ok {
		_spec.SetField(systemconfiguration.FieldWallpaperID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WallpaperFilename(); ok {
		_spec.SetField(systemconfiguration.FieldWallpaperFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.WallpaperMimeType(); ok {
		_spec.SetField(systemconfiguration.FieldWallpaperMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemconfiguration.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SystemConfiguration{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemconfiguration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
