// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/predicate"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/workflowrun"
)

// WorkflowRunUpdate is the builder for updating WorkflowRun entities.
type WorkflowRunUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowRunMutation
}

// Where appends a list predicates to the WorkflowRunUpdate builder.
func (_u *WorkflowRunUpdate) Where(ps ...predicate.WorkflowRun) *WorkflowRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *WorkflowRunUpdate) SetSessionID(v string) *WorkflowRunUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableSessionID(v *string) *WorkflowRunUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetWorkflowDefinitionID sets the "workflow_definition_id" field.
func (_u *WorkflowRunUpdate) SetWorkflowDefinitionID(v string) *WorkflowRunUpdate {
	_u.mutation.SetWorkflowDefinitionID(v)
	return _u
}

// SetNillableWorkflowDefinitionID sets the "workflow_definition_id" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableWorkflowDefinitionID(v *string) *WorkflowRunUpdate {
	if v != nil {
		_u.SetWorkflowDefinitionID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkflowRunUpdate) SetStatus(v string) *WorkflowRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableStatus(v *string) *WorkflowRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentNodeID sets the "current_node_id" field.
func (_u *WorkflowRunUpdate) SetCurrentNodeID(v string) *WorkflowRunUpdate {
	_u.mutation.SetCurrentNodeID(v)
	return _u
}

// SetNillableCurrentNodeID sets the "current_node_id" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableCurrentNodeID(v *string) *WorkflowRunUpdate {
	if v != nil {
		_u.SetCurrentNodeID(*v)
	}
	return _u
}

// SetContext sets the "context" field.
func (_u *WorkflowRunUpdate) SetContext(v map[string]interface{}) *WorkflowRunUpdate {
	_u.mutation.SetContext(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *WorkflowRunUpdate) SetStartedAt(v time.Time) *WorkflowRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableStartedAt(v *time.Time) *WorkflowRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *WorkflowRunUpdate) ClearStartedAt() *WorkflowRunUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetStoppedAt sets the "stopped_at" field.
func (_u *WorkflowRunUpdate) SetStoppedAt(v time.Time) *WorkflowRunUpdate {
	_u.mutation.SetStoppedAt(v)
	return _u
}

// SetNillableStoppedAt sets the "stopped_at" field if the given value is not nil.
func (_u *WorkflowRunUpdate) SetNillableStoppedAt(v *time.Time) *WorkflowRunUpdate {
	if v != nil {
		_u.SetStoppedAt(*v)
	}
	return _u
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (_u *WorkflowRunUpdate) ClearStoppedAt() *WorkflowRunUpdate {
	_u.mutation.ClearStoppedAt()
	return _u
}

// Mutation returns the WorkflowRunMutation object of the builder.
func (_u *WorkflowRunUpdate) Mutation() *WorkflowRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowRunUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := workflowrun.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkflowDefinitionID(); ok {
		if err := workflowrun.WorkflowDefinitionIDValidator(v); err != nil {
			return &ValidationError{Name: "workflow_definition_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.workflow_definition_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := workflowrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.status": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkflowRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowrun.Table, workflowrun.Columns, sqlgraph.NewFieldSpec(workflowrun.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(workflowrun.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkflowDefinitionID(); ok {
		_spec.SetField(workflowrun.FieldWorkflowDefinitionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workflowrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentNodeID(); ok {
		_spec.SetField(workflowrun.FieldCurrentNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Context(); ok {
		_spec.SetField(workflowrun.FieldContext, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(workflowrun.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(workflowrun.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StoppedAt(); ok {
		_spec.SetField(workflowrun.FieldStoppedAt, field.TypeTime, value)
	}
	if _u.mutation.StoppedAtCleared() {
		_spec.ClearField(workflowrun.FieldStoppedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowRunUpdateOne is the builder for updating a single WorkflowRun entity.
type WorkflowRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowRunMutation
}

// SetSessionID sets the "session_id" field.
func (_u *WorkflowRunUpdateOne) SetSessionID(v string) *WorkflowRunUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableSessionID(v *string) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetWorkflowDefinitionID sets the "workflow_definition_id" field.
func (_u *WorkflowRunUpdateOne) SetWorkflowDefinitionID(v string) *WorkflowRunUpdateOne {
	_u.mutation.SetWorkflowDefinitionID(v)
	return _u
}

// SetNillableWorkflowDefinitionID sets the "workflow_definition_id" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableWorkflowDefinitionID(v *string) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetWorkflowDefinitionID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkflowRunUpdateOne) SetStatus(v string) *WorkflowRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableStatus(v *string) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCurrentNodeID sets the "current_node_id" field.
func (_u *WorkflowRunUpdateOne) SetCurrentNodeID(v string) *WorkflowRunUpdateOne {
	_u.mutation.SetCurrentNodeID(v)
	return _u
}

// SetNillableCurrentNodeID sets the "current_node_id" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableCurrentNodeID(v *string) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetCurrentNodeID(*v)
	}
	return _u
}

// SetContext sets the "context" field.
func (_u *WorkflowRunUpdateOne) SetContext(v map[string]interface{}) *WorkflowRunUpdateOne {
	_u.mutation.SetContext(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *WorkflowRunUpdateOne) SetStartedAt(v time.Time) *WorkflowRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableStartedAt(v *time.Time) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *WorkflowRunUpdateOne) ClearStartedAt() *WorkflowRunUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetStoppedAt sets the "stopped_at" field.
func (_u *WorkflowRunUpdateOne) SetStoppedAt(v time.Time) *WorkflowRunUpdateOne {
	_u.mutation.SetStoppedAt(v)
	return _u
}

// SetNillableStoppedAt sets the "stopped_at" field if the given value is not nil.
func (_u *WorkflowRunUpdateOne) SetNillableStoppedAt(v *time.Time) *WorkflowRunUpdateOne {
	if v != nil {
		_u.SetStoppedAt(*v)
	}
	return _u
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (_u *WorkflowRunUpdateOne) ClearStoppedAt() *WorkflowRunUpdateOne {
	_u.mutation.ClearStoppedAt()
	return _u
}

// Mutation returns the WorkflowRunMutation object of the builder.
func (_u *WorkflowRunUpdateOne) Mutation() *WorkflowRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkflowRunUpdate builder.
func (_u *WorkflowRunUpdateOne) Where(ps ...predicate.WorkflowRun) *WorkflowRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowRunUpdateOne) Select(field string, fields ...string) *WorkflowRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkflowRun entity.
func (_u *WorkflowRunUpdateOne) Save(ctx context.Context) (*WorkflowRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowRunUpdateOne) SaveX(ctx context.Context) *WorkflowRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowRunUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := workflowrun.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkflowDefinitionID(); ok {
		if err := workflowrun.WorkflowDefinitionIDValidator(v); err != nil {
			return &ValidationError{Name: "workflow_definition_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.workflow_definition_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := workflowrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "WorkflowRun.status": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkflowRunUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowrun.Table, workflowrun.Columns, sqlgraph.NewFieldSpec(workflowrun.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowrun.FieldID)
		for _, f := range fields {
			if !workflowrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(workflowrun.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.WorkflowDefinitionID(); ok {
		_spec.SetField(workflowrun.FieldWorkflowDefinitionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workflowrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentNodeID(); ok {
		_spec.SetField(workflowrun.FieldCurrentNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Context(); ok {
		_spec.SetField(workflowrun.FieldContext, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(workflowrun.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(workflowrun.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StoppedAt(); ok {
		_spec.SetField(workflowrun.FieldStoppedAt, field.TypeTime, value)
	}
	if _u.mutation.StoppedAtCleared() {
		_spec.ClearField(workflowrun.FieldStoppedAt, field.TypeTime)
	}
	_node = &WorkflowRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
