// Code generated by ent, DO NOT EDIT.

package workflowrun

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the workflowrun type in the database.
	Label = "workflow_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldWorkflowDefinitionID holds the string denoting the workflow_definition_id field in the database.
	FieldWorkflowDefinitionID = "workflow_definition_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCurrentNodeID holds the string denoting the current_node_id field in the database.
	FieldCurrentNodeID = "current_node_id"
	// FieldContext holds the string denoting the context field in the database.
	FieldContext = "context"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldStoppedAt holds the string denoting the stopped_at field in the database.
	FieldStoppedAt = "stopped_at"
	// Table holds the table name of the workflowrun in the database.
	Table = "workflow_runs"
)

// Columns holds all SQL columns for workflowrun fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldWorkflowDefinitionID,
	FieldStatus,
	FieldCurrentNodeID,
	FieldContext,
	FieldStartedAt,
	FieldStoppedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	SessionIDValidator func(string) error
	// WorkflowDefinitionIDValidator is a validator for the "workflow_definition_id" field. It is called by the builders before save.
	WorkflowDefinitionIDValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCurrentNodeID holds the default value on creation for the "current_node_id" field.
	DefaultCurrentNodeID string
	// DefaultContext holds the default value on creation for the "context" field.
	DefaultContext map[string]interface{}
)

// OrderOption defines the ordering options for the WorkflowRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByWorkflowDefinitionID orders the results by the workflow_definition_id field.
func ByWorkflowDefinitionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowDefinitionID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCurrentNodeID orders the results by the current_node_id field.
func ByCurrentNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentNodeID, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByStoppedAt orders the results by the stopped_at field.
func ByStoppedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoppedAt, opts...).ToFunc()
}
