// Code generated by ent, DO NOT EDIT.

package questionbatch

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the questionbatch type in the database.
	Label = "question_batch"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldWorkflowRunID holds the string denoting the workflow_run_id field in the database.
	FieldWorkflowRunID = "workflow_run_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDeliveryStatus holds the string denoting the delivery_status field in the database.
	FieldDeliveryStatus = "delivery_status"
	// FieldQuestions holds the string denoting the questions field in the database.
	FieldQuestions = "questions"
	// FieldAnswers holds the string denoting the answers field in the database.
	FieldAnswers = "answers"
	// FieldCancelReason holds the string denoting the cancel_reason field in the database.
	FieldCancelReason = "cancel_reason"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldAnsweredAt holds the string denoting the answered_at field in the database.
	FieldAnsweredAt = "answered_at"
	// Table holds the table name of the questionbatch in the database.
	Table = "question_batches"
)

// Columns holds all SQL columns for questionbatch fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldWorkflowRunID,
	FieldStatus,
	FieldDeliveryStatus,
	FieldQuestions,
	FieldAnswers,
	FieldCancelReason,
	FieldCreatedAt,
	FieldAnsweredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	SessionIDValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultDeliveryStatus holds the default value on creation for the "delivery_status" field.
	DefaultDeliveryStatus string
	// DefaultQuestions holds the default value on creation for the "questions" field.
	DefaultQuestions []map[string]interface{}
	// DefaultAnswers holds the default value on creation for the "answers" field.
	DefaultAnswers []map[string]interface{}
	// DefaultCancelReason holds the default value on creation for the "cancel_reason" field.
	DefaultCancelReason string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the QuestionBatch queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByWorkflowRunID orders the results by the workflow_run_id field.
func ByWorkflowRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowRunID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDeliveryStatus orders the results by the delivery_status field.
func ByDeliveryStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryStatus, opts...).ToFunc()
}

// ByCancelReason orders the results by the cancel_reason field.
func ByCancelReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAnsweredAt orders the results by the answered_at field.
func ByAnsweredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnsweredAt, opts...).ToFunc()
}
