// Code generated by ent, DO NOT EDIT.

package mergerecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the mergerecord type in the database.
	Label = "merge_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldNodeRunID holds the string denoting the node_run_id field in the database.
	FieldNodeRunID = "node_run_id"
	// FieldStrategy holds the string denoting the strategy field in the database.
	FieldStrategy = "strategy"
	// FieldBaseBranch holds the string denoting the base_branch field in the database.
	FieldBaseBranch = "base_branch"
	// FieldWorktreeBranch holds the string denoting the worktree_branch field in the database.
	FieldWorktreeBranch = "worktree_branch"
	// FieldBaseCommit holds the string denoting the base_commit field in the database.
	FieldBaseCommit = "base_commit"
	// FieldHeadCommit holds the string denoting the head_commit field in the database.
	FieldHeadCommit = "head_commit"
	// FieldMergeCommit holds the string denoting the merge_commit field in the database.
	FieldMergeCommit = "merge_commit"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFailureCode holds the string denoting the failure_code field in the database.
	FieldFailureCode = "failure_code"
	// FieldFailureReason holds the string denoting the failure_reason field in the database.
	FieldFailureReason = "failure_reason"
	// FieldMergedAt holds the string denoting the merged_at field in the database.
	FieldMergedAt = "merged_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the mergerecord in the database.
	Table = "merge_records"
)

// Columns holds all SQL columns for mergerecord fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldNodeRunID,
	FieldStrategy,
	FieldBaseBranch,
	FieldWorktreeBranch,
	FieldBaseCommit,
	FieldHeadCommit,
	FieldMergeCommit,
	FieldStatus,
	FieldFailureCode,
	FieldFailureReason,
	FieldMergedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	SessionIDValidator func(string) error
	// DefaultStrategy holds the default value on creation for the "strategy" field.
	DefaultStrategy string
	// DefaultBaseBranch holds the default value on creation for the "base_branch" field.
	DefaultBaseBranch string
	// DefaultWorktreeBranch holds the default value on creation for the "worktree_branch" field.
	DefaultWorktreeBranch string
	// DefaultBaseCommit holds the default value on creation for the "base_commit" field.
	DefaultBaseCommit string
	// DefaultHeadCommit holds the default value on creation for the "head_commit" field.
	DefaultHeadCommit string
	// DefaultMergeCommit holds the default value on creation for the "merge_commit" field.
	DefaultMergeCommit string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultFailureCode holds the default value on creation for the "failure_code" field.
	DefaultFailureCode string
	// DefaultFailureReason holds the default value on creation for the "failure_reason" field.
	DefaultFailureReason string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the MergeRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByNodeRunID orders the results by the node_run_id field.
func ByNodeRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeRunID, opts...).ToFunc()
}

// ByStrategy orders the results by the strategy field.
func ByStrategy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategy, opts...).ToFunc()
}

// ByBaseBranch orders the results by the base_branch field.
func ByBaseBranch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseBranch, opts...).ToFunc()
}

// ByWorktreeBranch orders the results by the worktree_branch field.
func ByWorktreeBranch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorktreeBranch, opts...).ToFunc()
}

// ByBaseCommit orders the results by the base_commit field.
func ByBaseCommit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseCommit, opts...).ToFunc()
}

// ByHeadCommit orders the results by the head_commit field.
func ByHeadCommit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeadCommit, opts...).ToFunc()
}

// ByMergeCommit orders the results by the merge_commit field.
func ByMergeCommit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMergeCommit, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFailureCode orders the results by the failure_code field.
func ByFailureCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureCode, opts...).ToFunc()
}

// ByFailureReason orders the results by the failure_reason field.
func ByFailureReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureReason, opts...).ToFunc()
}

// ByMergedAt orders the results by the merged_at field.
func ByMergedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMergedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
