// Code generated by ent, DO NOT EDIT.

package pushsubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the pushsubscription type in the database.
	Label = "push_subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrincipalKeyHash holds the string denoting the principal_key_hash field in the database.
	FieldPrincipalKeyHash = "principal_key_hash"
	// FieldEndpointHash holds the string denoting the endpoint_hash field in the database.
	FieldEndpointHash = "endpoint_hash"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldP256dh holds the string denoting the p256dh field in the database.
	FieldP256dh = "p256dh"
	// FieldAuth holds the string denoting the auth field in the database.
	FieldAuth = "auth"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the pushsubscription in the database.
	Table = "push_subscriptions"
)

// Columns holds all SQL columns for pushsubscription fields.
var Columns = []string{
	FieldID,
	FieldPrincipalKeyHash,
	FieldEndpointHash,
	FieldEndpoint,
	FieldP256dh,
	FieldAuth,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PrincipalKeyHashValidator is a validator for the "principal_key_hash" field. It is called by the builders before save.
	PrincipalKeyHashValidator func(string) error
	// EndpointHashValidator is a validator for the "endpoint_hash" field. It is called by the builders before save.
	EndpointHashValidator func(string) error
	// EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	EndpointValidator func(string) error
	// P256dhValidator is a validator for the "p256dh" field. It is called by the builders before save.
	P256dhValidator func(string) error
	// AuthValidator is a validator for the "auth" field. It is called by the builders before save.
	AuthValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PushSubscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrincipalKeyHash orders the results by the principal_key_hash field.
func ByPrincipalKeyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrincipalKeyHash, opts...).ToFunc()
}

// ByEndpointHash orders the results by the endpoint_hash field.
func ByEndpointHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpointHash, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByP256dh orders the results by the p256dh field.
func ByP256dh(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldP256dh, opts...).ToFunc()
}

// ByAuth orders the results by the auth field.
func ByAuth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuth, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
