// Code generated by ent, DO NOT EDIT.

package mindmapgraph

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldContainsFold(FieldID, id))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MindMapGraph) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MindMapGraph) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MindMapGraph) predicate.MindMapGraph {
	return predicate.MindMapGraph(sql.NotPredicates(p))
}
