// Code generated by ent, DO NOT EDIT.

package codextranscriptsource

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the codextranscriptsource type in the database.
	Label = "codex_transcript_source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCodexSessionID holds the string denoting the codex_session_id field in the database.
	FieldCodexSessionID = "codex_session_id"
	// FieldRelativePath holds the string denoting the relative_path field in the database.
	FieldRelativePath = "relative_path"
	// FieldBoundAt holds the string denoting the bound_at field in the database.
	FieldBoundAt = "bound_at"
	// Table holds the table name of the codextranscriptsource in the database.
	Table = "codex_transcript_sources"
)

// Columns holds all SQL columns for codextranscriptsource fields.
var Columns = []string{
	FieldID,
	FieldCodexSessionID,
	FieldRelativePath,
	FieldBoundAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RelativePathValidator is a validator for the "relative_path" field. It is called by the builders before save.
	RelativePathValidator func(string) error
	// DefaultBoundAt holds the default value on creation for the "bound_at" field.
	DefaultBoundAt func() time.Time
)

// OrderOption defines the ordering options for the CodexTranscriptSource queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCodexSessionID orders the results by the codex_session_id field.
func ByCodexSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodexSessionID, opts...).ToFunc()
}

// ByRelativePath orders the results by the relative_path field.
func ByRelativePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRelativePath, opts...).ToFunc()
}

// ByBoundAt orders the results by the bound_at field.
func ByBoundAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoundAt, opts...).ToFunc()
}
