// Code generated by ent, DO NOT EDIT.

package sessionside

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/nzlov/anycode/internal/infra/entstore/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContainsFold(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldSessionID, v))
}

// ProcessRunID applies equality check predicate on the "process_run_id" field. It's identical to ProcessRunIDEQ.
func ProcessRunID(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldProcessRunID, v))
}

// TurnID applies equality check predicate on the "turn_id" field. It's identical to TurnIDEQ.
func TurnID(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldTurnID, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldPrompt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldStatus, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldError, v))
}

// TurnIndex applies equality check predicate on the "turn_index" field. It's identical to TurnIndexEQ.
func TurnIndex(v int) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldTurnIndex, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldUpdatedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContainsFold(FieldSessionID, v))
}

// ProcessRunIDEQ applies the EQ predicate on the "process_run_id" field.
func ProcessRunIDEQ(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldProcessRunID, v))
}

// ProcessRunIDNEQ applies the NEQ predicate on the "process_run_id" field.
func ProcessRunIDNEQ(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNEQ(FieldProcessRunID, v))
}

// ProcessRunIDIn applies the In predicate on the "process_run_id" field.
func ProcessRunIDIn(vs ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldIn(FieldProcessRunID, vs...))
}

// ProcessRunIDNotIn applies the NotIn predicate on the "process_run_id" field.
func ProcessRunIDNotIn(vs ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNotIn(FieldProcessRunID, vs...))
}

// ProcessRunIDGT applies the GT predicate on the "process_run_id" field.
func ProcessRunIDGT(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGT(FieldProcessRunID, v))
}

// ProcessRunIDGTE applies the GTE predicate on the "process_run_id" field.
func ProcessRunIDGTE(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGTE(FieldProcessRunID, v))
}

// ProcessRunIDLT applies the LT predicate on the "process_run_id" field.
func ProcessRunIDLT(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLT(FieldProcessRunID, v))
}

// ProcessRunIDLTE applies the LTE predicate on the "process_run_id" field.
func ProcessRunIDLTE(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLTE(FieldProcessRunID, v))
}

// ProcessRunIDContains applies the Contains predicate on the "process_run_id" field.
func ProcessRunIDContains(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContains(FieldProcessRunID, v))
}

// ProcessRunIDHasPrefix applies the HasPrefix predicate on the "process_run_id" field.
func ProcessRunIDHasPrefix(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldHasPrefix(FieldProcessRunID, v))
}

// ProcessRunIDHasSuffix applies the HasSuffix predicate on the "process_run_id" field.
func ProcessRunIDHasSuffix(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldHasSuffix(FieldProcessRunID, v))
}

// ProcessRunIDEqualFold applies the EqualFold predicate on the "process_run_id" field.
func ProcessRunIDEqualFold(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEqualFold(FieldProcessRunID, v))
}

// ProcessRunIDContainsFold applies the ContainsFold predicate on the "process_run_id" field.
func ProcessRunIDContainsFold(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContainsFold(FieldProcessRunID, v))
}

// TurnIDEQ applies the EQ predicate on the "turn_id" field.
func TurnIDEQ(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldTurnID, v))
}

// TurnIDNEQ applies the NEQ predicate on the "turn_id" field.
func TurnIDNEQ(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNEQ(FieldTurnID, v))
}

// TurnIDIn applies the In predicate on the "turn_id" field.
func TurnIDIn(vs ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldIn(FieldTurnID, vs...))
}

// TurnIDNotIn applies the NotIn predicate on the "turn_id" field.
func TurnIDNotIn(vs ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNotIn(FieldTurnID, vs...))
}

// TurnIDGT applies the GT predicate on the "turn_id" field.
func TurnIDGT(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGT(FieldTurnID, v))
}

// TurnIDGTE applies the GTE predicate on the "turn_id" field.
func TurnIDGTE(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGTE(FieldTurnID, v))
}

// TurnIDLT applies the LT predicate on the "turn_id" field.
func TurnIDLT(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLT(FieldTurnID, v))
}

// TurnIDLTE applies the LTE predicate on the "turn_id" field.
func TurnIDLTE(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLTE(FieldTurnID, v))
}

// TurnIDContains applies the Contains predicate on the "turn_id" field.
func TurnIDContains(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContains(FieldTurnID, v))
}

// TurnIDHasPrefix applies the HasPrefix predicate on the "turn_id" field.
func TurnIDHasPrefix(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldHasPrefix(FieldTurnID, v))
}

// TurnIDHasSuffix applies the HasSuffix predicate on the "turn_id" field.
func TurnIDHasSuffix(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldHasSuffix(FieldTurnID, v))
}

// TurnIDEqualFold applies the EqualFold predicate on the "turn_id" field.
func TurnIDEqualFold(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEqualFold(FieldTurnID, v))
}

// TurnIDContainsFold applies the ContainsFold predicate on the "turn_id" field.
func TurnIDContainsFold(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContainsFold(FieldTurnID, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContainsFold(FieldPrompt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldHasSuffix(FieldError, v))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldContainsFold(FieldError, v))
}

// TurnIndexEQ applies the EQ predicate on the "turn_index" field.
func TurnIndexEQ(v int) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldTurnIndex, v))
}

// TurnIndexNEQ applies the NEQ predicate on the "turn_index" field.
func TurnIndexNEQ(v int) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNEQ(FieldTurnIndex, v))
}

// TurnIndexIn applies the In predicate on the "turn_index" field.
func TurnIndexIn(vs ...int) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldIn(FieldTurnIndex, vs...))
}

// TurnIndexNotIn applies the NotIn predicate on the "turn_index" field.
func TurnIndexNotIn(vs ...int) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNotIn(FieldTurnIndex, vs...))
}

// TurnIndexGT applies the GT predicate on the "turn_index" field.
func TurnIndexGT(v int) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGT(FieldTurnIndex, v))
}

// TurnIndexGTE applies the GTE predicate on the "turn_index" field.
func TurnIndexGTE(v int) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGTE(FieldTurnIndex, v))
}

// TurnIndexLT applies the LT predicate on the "turn_index" field.
func TurnIndexLT(v int) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLT(FieldTurnIndex, v))
}

// TurnIndexLTE applies the LTE predicate on the "turn_index" field.
func TurnIndexLTE(v int) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLTE(FieldTurnIndex, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SessionSide {
	return predicate.SessionSide(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SessionSide) predicate.SessionSide {
	return predicate.SessionSide(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SessionSide) predicate.SessionSide {
	return predicate.SessionSide(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SessionSide) predicate.SessionSide {
	return predicate.SessionSide(sql.NotPredicates(p))
}
